add input for using egosdk as a flag in run-system-tests-tokenomics-action.

diff --git a/run-system-tests-tokenomics/action.yml b/run-system-tests-tokenomics/action.yml
--- a/run-system-tests-tokenomics/action.yml
+++ b/run-system-tests-tokenomics/action.yml
@@ -38,6 +38,10 @@ inputs:
     required: true
     default: "NONE"
     description: 'custom gosdk version. Will upgrade CLI branches with this before running tests'
+  use_egosdk:
+    required: false
+    default: "false"
+    description: 'use egosdk instead of gosdk for enterprise blobbers network'
   tokenomics_test_filter:
     required: false
     default: ""
@@ -91,8 +95,15 @@ runs:
         ./check-params.sh "${{inputs.zwallet_cli_branch}}"      "${{ env.SNAPSHOT_BRANCH_ZWALLETCLI }}"   "ZWALLET_BRANCH"
         ./check-params.sh "${{inputs.system_tests_branch}}"     "${{ env.SNAPSHOT_BRANCH_SYSTEM_TEST }}"  "SYSTEM_TESTS_BRANCH"
         ./check-params.sh "${{inputs.s3_migration_cli_branch}}" "${{ env.SNAPSHOT_BRANCH_S3-MIGRATION }}" "S3_MIGRATION_BRANCH"
+        
+        if [[ ${{inputs.use_egosdk}}== "false" ]]
+        then 
         ./check-params.sh "${{inputs.custom_go_sdk_version}}"   "${{ env.SNAPSHOT_BRANCH_GOSDK }}"        "GOSDK_VERSION"
+        else
+        ./check-param.sh "${{inputs.custom_go_sdk_version}}"    "${{ env.SNAPSHOT_BRANCH_EGOSDK }}"       "GOSDK_VERSION"
+        fi
 
+        echo "USE_EGOSDK=$(echo ${{inputs.use_egosdk}})" >> $GITHUB_ENV
         echo "NETWORK_URL=$(echo ${{ inputs.network }})" >> $GITHUB_ENV
         echo "GOMODCACHE=/root/actions-runner${RUNNER_NAME:(-1)}/_work/_tool/go/pkg/mod" >> $GITHUB_ENV
         echo "GOCACHE=/root/actions-runner${RUNNER_NAME:(-1)}/_work/_tool/.cache/go-build" >> $GITHUB_ENV
@@ -127,7 +138,14 @@ runs:
         echo "0wallet CLI branch:       [${{ env.ZWALLET_BRANCH }}]"
         echo "s3 migration CLI branch:  [${{ env.S3_MIGRATION_BRANCH }}]"
         echo "Ethereum node URL:        [https://virtual.mainnet.rpc.tenderly.co/${{ inputs.TENDERLY_VIRTUAL_TESTNET_RPC_ID }}]"
-        echo "Custom gosdk version:     [${{ env.GOSDK_VERSION }}]"
+        
+        if [[ "${{env.USE_EGOSDK}}" == "false" ]]
+        then
+          echo "Custom gosdk version:     [${{ env.GOSDK_VERSION }}]"
+        else
+          echo "Custom egosdk version:    [${{ env.GOSDK_VERSION }}]"
+        fi
+        
         echo "Test file filter:         [${{ inputs.test_file_filter }}]"
         echo "Running Tokenomics tests: [${{ env.RUN_TOKENOMICS_SYSTEM_TESTS }}]"
 
@@ -205,7 +223,13 @@ runs:
         echo "=============================================================="
         echo
 
-        GOSDK_HEAD=$(curl -s -H "Authorization: token ${{ inputs.svc_account_secret }}" https://api.github.com/repos/0chain/gosdk/git/refs/heads/${{ env.GOSDK_VERSION }} | jq -r '.object.sha')
+        if [[ "${{env.USE_EGOSDK}}" == "false" ]];
+        then
+          GOSDK_HEAD=$(curl -s -H "Authorization: token ${{ inputs.svc_account_secret }}" https://api.github.com/repos/0chain/gosdk/git/refs/heads/${{ env.GOSDK_VERSION }} | jq -r '.object.sha')
+        else
+          GOSDK_HEAD=$(curl -s -H "Authorization: token ${{ inputs.svc_account_secret }}" https://api.github.com/repos/0chain/egosdk/git/refs/heads/${{ env.GOSDK_VERSION }} | jq -r '.object.sha')
+        fi
+        
         if [[ "$GOSDK_HEAD" == "null" ]]; then
             echo "[${{ env.GOSDK_VERSION }}] does not seem to be a valid branch (possibly a commit hash?). Will pass directly to go to resolve"
             GOSDK_HEAD="${{ env.GOSDK_VERSION }}"
@@ -213,7 +237,14 @@ runs:
 
         echo '#!/bin/bash
         echo "Upgrading [$2] to GOSDK [${{ env.GOSDK_VERSION }}($1)]"
-        go get github.com/0chain/gosdk@$1 || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ env.GOSDK_VERSION }}]" && exit 1; }
+        
+        if [[ "${{env.USE_EGOSDK}}" == "false" ]];
+        then
+          go get github.com/0chain/gosdk@$1 || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ env.GOSDK_VERSION }}]" && exit 1; }
+        else
+          go get github.com/0chain/egosdk@$1 || { echo "::error title=Failed to retrieve egosdk::failed to retrieve egosdk [${{ env.GOSDK_VERSION }}]" && exit 1; }
+        fi
+        
         go mod tidy || { echo "::error title=Failed to upgrade $2 gosdk::failed to upgrade $2 gosdk to [${{ env.GOSDK_VERSION }}]" && exit 1; }
         ' > ./upgrade-gosdk.sh;
         chmod 555 ./upgrade-gosdk.sh
@@ -279,15 +310,21 @@ runs:
         (./zbox version --configDir ./config --config ./zbox_config.yaml --wallet ../ignore --silent | grep -A2 'Version info' | sed "s/Version info:/ZBox Version Info:/") || true
 
     - name: "Set up frontend tests"
-      if:  ${{ env.RUN_FRONTEND_TESTS == 'true' }}
+      if: ${{ env.RUN_FRONTEND_TESTS == 'true' }}
       shell: 'script --return --quiet --command "bash {0}"'
       run: |
         echo
         echo "======================================================"
         echo "SETTING WASM TESTS:"
         echo "======================================================"
-        git clone -q https://github.com/0chain/gosdk.git
-        cd gosdk
+        if [[ "${{env.USE_EGOSDK}}" == "false" ]];
+        then
+          git clone -q https://github.com/0chain/gosdk.git
+          cd gosdk
+        else
+          git clone -q https://github.com/0chain/egosdk.git
+          cd egosdk
+        fi
 
         if [[ -n "${{  env.GOSDK_VERSION }}" && "${{  env.GOSDK_VERSION }}" != "NONE" ]];
         then
@@ -296,8 +333,8 @@ runs:
 
         cd ..
 
-    - name: Run frontend Tests
-      if:  ${{ env.RUN_FRONTEND_TESTS == 'true' && env.RUN_SUBSET_OF_TESTS == 'false' }}
+    - name: Run frontend Tests with normal gosdk.
+      if: ${{ env.RUN_FRONTEND_TESTS == 'true' && inputs.use_egosdk == 'false' && env.RUN_SUBSET_OF_TESTS == 'false' }}
       uses: cypress-io/github-action@v5
       with:
         working-directory: ./gosdk/wasmsdk/cypress
@@ -305,11 +342,18 @@ runs:
         install-command: yarn start:system-tests
         start: yarn start
 
-
+    - name: Run frontend Tests with egosdk.
+      if: ${{ env.RUN_FRONTEND_TESTS == 'true' && inputs.use_egosdk == 'true' && env.RUN_SUBSET_OF_TESTS == 'false' }}
+      uses: cypress-io/github-action@v5
+      with:
+        working-directory: ./egosdk/wasmsdk/cypress
+        record: false
+        install-command: yarn start:system-tests
+        start: yarn start
 
     - name: "Run Tokenomics System Tests"
       shell: 'script --return --quiet --command "bash {0}"'
-      if:  ${{ env.RUN_TOKENOMICS_SYSTEM_TESTS == 'true' && env.RUN_TOKENOMICS_SUBSET_OF_TESTS == 'false' && 'true' == 'false' }}
+      if: ${{ env.RUN_TOKENOMICS_SYSTEM_TESTS == 'true' && env.RUN_TOKENOMICS_SUBSET_OF_TESTS == 'false' && 'true' == 'false' }}
       run: |
         echo
         echo "======================================================"
@@ -350,7 +394,7 @@ runs:
         exit $tokenomics_system_tests_exit_code
 
     - name: "Run subset of TOKENOMICS System Tests"
-      if:  ${{ env.RUN_TOKENOMICS_SUBSET_OF_TESTS == 'true' }}
+      if: ${{ env.RUN_TOKENOMICS_SUBSET_OF_TESTS == 'true' }}
       shell: 'script --return --quiet --command "bash {0}"'
       run: |
         echo
