log time

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -134,8 +134,13 @@ runs:
         sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl > build.log 2>&1 || { cat build.log && echo "::error title=Failed to install test dependency::failed to install youtube-dl" && exit 1; }
         sudo chmod a+rx /usr/local/bin/youtube-dl
         echo "installing ffmpeg..."
-        sudo apt update > build.log 2>&1 || { cat build.log && exit 1; }
-        sudo apt install -y ffmpeg > build.log 2>&1 || { cat build.log && echo "::error title=Failed to install test dependency::failed to install ffmpeg" && exit 1; }
+        start=`date +%s`
+        sudo apt update > build.log 2>&1 || { cat build.log && exit 1; } &
+        sudo apt install -y ffmpeg > build.log 2>&1 || { cat build.log && echo "::error title=Failed to install test dependency::failed to install ffmpeg" && exit 1; } &
+        wait
+        end=`date +%s`
+        runtime=$((end - start))
+        echo "Runtime of installing required binaries was: $runtime"
         echo "Test dependencies install SUCCESS!"
 
     - name: "Build CLI Binaries"
