break system stability check to another step

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -231,17 +231,6 @@ runs:
         cp -R ./${{ env.BRANCH_DIR }}/${GITHUB_SHA} ./${{ env.BRANCH_DIR }}/latest
         echo "TESTS_RAN=true" >> $GITHUB_ENV
 
-        if [ -n "${{ env.NAMESPACE }}" ];
-          then
-            kubectl get pods -A --kubeconfig ../kube/${{ env.NAMESPACE }}-config | awk '$5>0' |  awk '$2 ~ /.*miner|sharder|blobber|validator|NAME|RESTARTS.*/' | awk {'print $2" " $5'} > pod_status_post_test_run.txt
-            echo "Pod status pre test run (some restarts are normal as the network stabilises):"
-            cat pod_status_pre_test_run.txt
-            echo "Pod status post test run (no more further restarts should have taken place for the network to be considered stable):"
-            cat pod_status_post_test_run.txt
-          else
-            echo "NOT preforming system stability check because network was not deployed as part of this test run"
-        fi
-
         if [[ $system_tests_exit_code == 0 ]];
           then
             echo TESTS_PASSED=true >> $GITHUB_ENV
@@ -250,20 +239,16 @@ runs:
             echo "::error title=System tests faled!::System tests failed. Ensure tests are running against the correct images/branches and rule out any possible code issues before attempting a re-run"
         fi
 
-        if [[ -n "${{ env.NAMESPACE }}" && "$(md5 -q pod_status_pre_test_run.txt)" == "$(md5 -q pod_status_post_test_run.txt)" ]];
-          then
-            echo PODS_CRASHED=true >> $GITHUB_ENV
-            echo "::error title=System crashed during test run!::Pods were restarted during the test run. Therefore the build is NOT STABLE. Please investigate whey the system is crashing."
-          else
-            echo PODS_CRASHED=false >> $GITHUB_ENV
-        fi
-
         exit $system_tests_exit_code
 
     - name: "Run subset of CLI System Tests"
       if:  ${{ env.RUN_SUBSET_OF_TESTS == 'true' }}
       shell: 'script --return --quiet --command "bash {0}"'
       run: |
+        if [ -n "${{ env.NAMESPACE }}" ]; then
+          kubectl get pods -A --kubeconfig ../kube/${{ env.NAMESPACE }}-config | awk '$5>0' |  awk '$2 ~ /.*miner|sharder|blobber|validator|NAME|RESTARTS.*/' | awk {'print $2" " $5'} > pod_status_pre_test_run.txt
+        fi
+
         cd tests/cli_tests
 
         testFiles=$(echo ${{ inputs.test_file_filter }} | sed 's/,/ /g')
@@ -294,10 +279,6 @@ runs:
         echo "======================================================"
         echo
 
-        if [ -n "${{ env.NAMESPACE }}" ]; then
-          kubectl get pods -A --kubeconfig ../kube/${{ env.NAMESPACE }}-config | awk '$5>0' |  awk '$2 ~ /.*miner|sharder|blobber|validator|NAME|RESTARTS.*/' | awk {'print $2" " $5'} > pod_status_pre_test_run.txt
-        fi
-
         system_tests_exit_code=0
         ~/go/bin/gotestsum --jsonfile test-output.json --hide-summary=output --format testname ${{ env.SHOULD_RETRY_FAILURES }} --raw-command -- ./SUBSET_TEST_RUNNER_COMMAND.sh || system_tests_exit_code=$?
         cat test-output.json | ~/go/bin/go-test-report --groupSize 1 --output ${{ env.BRANCH_DIR }}/${GITHUB_SHA}/index.html --title "Subset of 0Chain System test suite [${{ env.BRANCH_DIR }}/${GITHUB_SHA:0:8}] ran against [${{ env.NETWORK_URL }}] at [${{ env.TEST_TIME }}]"
@@ -305,32 +286,12 @@ runs:
         cp -R ./${{ env.BRANCH_DIR }}/${GITHUB_SHA} ./${{ env.BRANCH_DIR }}/latest
         echo "TESTS_RAN=true" >> $GITHUB_ENV
 
-        if [ -n "${{ env.NAMESPACE }}" ];
-          then
-            kubectl get pods -A --kubeconfig ../kube/${{ env.NAMESPACE }}-config | awk '$5>0' |  awk '$2 ~ /.*miner|sharder|blobber|validator|NAME|RESTARTS.*/' | awk {'print $2" " $5'} > pod_status_post_test_run.txt
-            echo "Pod status pre test run (some restarts are normal as the network stabilises):"
-            cat pod_status_pre_test_run.txt
-            echo "Pod status post test run (no more further restarts should have taken place for the network to be considered stable):"
-            cat pod_status_post_test_run.txt
-          else
-            echo "NOT preforming system stability check because network was not deployed as part of this test run"
-        fi
-
         if [[ $system_tests_exit_code == 0 ]];
           then
             echo TESTS_PASSED=true >> $GITHUB_ENV
           else
             echo TESTS_PASSED=false >> $GITHUB_ENV
             echo "::error title=System tests faled!::System tests failed. Ensure tests are running against the correct images/branches and rule out any possible code issues before attempting a re-run"
-        fi
-
-        if [[ -n "${{ env.NAMESPACE }}" && "$(md5 -q pod_status_pre_test_run.txt)" == "$(md5 -q pod_status_post_test_run.txt)" ]];
-          then
-            echo PODS_CRASHED=true >> $GITHUB_ENV
-            echo "::error title=System crashed during test run!::Pods were restarted during the test run. Therefore the build is NOT STABLE. Please investigate whey the system is crashing."
-            exit 1
-          else
-            echo PODS_CRASHED=false >> $GITHUB_ENV
         fi
 
         exit $system_tests_exit_code
@@ -345,6 +306,31 @@ runs:
           ./tests/cli_tests/config
           ./tests/cli_tests/cmdlog.log
           ./tests/cli_tests/${{ env.BRANCH_DIR }}/latest/index.html
+
+    - name: "System Stability Check"
+      if: ${{ always() && env.TESTS_RAN == 'true' }}
+      shell: 'script --return --quiet --command "bash {0}"'
+      run: |
+        if [ -n "${{ env.NAMESPACE }}" ];
+          then
+            kubectl get pods -A --kubeconfig ../kube/${{ env.NAMESPACE }}-config | awk '$5>0' |  awk '$2 ~ /.*miner|sharder|blobber|validator|NAME|RESTARTS.*/' | awk {'print $2" " $5'} > pod_status_post_test_run.txt
+            echo "Pod status pre test run (some restarts are normal as the network stabilises):"
+            cat pod_status_pre_test_run.txt
+            echo "Pod status post test run (no more further restarts should have taken place for the network to be considered stable):"
+            cat pod_status_post_test_run.txt
+          else
+            echo "NOT preforming system stability check because network was not deployed as part of this test run"
+        fi
+
+        if [[ -n "${{ env.NAMESPACE }}" && "$(md5sum pod_status_pre_test_run.txt | cut -f 1 -d ' ')" == "$(md5sum pod_status_post_test_run.txt | cut -f 1 -d ' ')" ]];
+          then
+            echo PODS_CRASHED=true >> $GITHUB_ENV
+            echo "::error title=System crashed during test run!::Pods were restarted during the test run. Therefore the build is NOT STABLE. Please investigate whey the system is crashing."
+            exit 1
+          else
+            echo "Pods did not crash during test run"
+            echo PODS_CRASHED=false >> $GITHUB_ENV
+        fi
 
     - name: "Run Flaky CLI System Tests"
       if:  ${{ env.TESTS_PASSED == 'true' && inputs.run_flaky_tests == 'true' }}
