set config file before running

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -169,31 +169,6 @@ runs:
         mv zbox ../tests/cli_tests
         echo "CLI build SUCCESS!"
 
-    - name: "Stake blobbers using zwalletCLI"
-      shell: 'script --return --quiet --command "bash {0}"'
-      run: |
-        echo '#!/bin/bash
-        echo
-        echo "==========================================================="
-        echo "STAKING BLOBBERS USING ZWALLETCLI & ZBOXCLI BINARIES"
-        echo "==========================================================="
-        echo
-        cd tests/cli_tests
-        ./zwallet register --silent > build.log 2>&1 || { cat build.log && echo "::error title=Failed to stake the blobbers::failed to register wallet through zwalletCLI built using above branch and goSDK." && exit 1; }
-        for i in {1..6}
-        do
-        ./zwallet faucet --methodName "pour" --input "{}" --tokens 2 --silent > build.log 2>&1 || { cat build.log && echo "::error title=Failed to stake the blobbers::failed to execute faucet through zwalletCLI built using above branch and goSDK." && exit 1; }
-        done
-
-        blobber_ids=( $(./zwallet getblobbers --silent | grep -o '[a-z0-9]\{64\}') )
-        for id in "${blobber_ids[@]}"
-        do
-          ./zbox sp-lock --blobber_id $id --tokens 2 --silent > build.log 2>&1 || { cat build.log && echo "::error title=Failed to stake the blobbers::failed to use sp-lock in zwalletCLI built using above branch and goSDK." && exit 1; }
-        done
-        ' > ./stake_blobbers.sh;
-        chmod 777 ./stake_blobbers.sh;
-        ./stake_blobbers.sh
-
     - name: "Set up system tests"
       shell: 'script --return --quiet --command "bash {0}"'
       run: |
@@ -221,6 +196,31 @@ runs:
         printf '#!/bin/bash\nset -o pipefail\nCONFIG_PATH=./zbox_config.yaml go test -timeout=60m -run  "^Test___Flaky.*$" ./... -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > FLAKY_TEST_RUNNER_COMMAND.sh && chmod 777 FLAKY_TEST_RUNNER_COMMAND.sh
         (./zwallet version --configDir ./config --config ./zbox_config.yaml --wallet ../ignore --silent | grep -A2 'Version info' | sed "s/Version info:/ZWallet Version Info:/") || true
         (./zbox version --configDir ./config --config ./zbox_config.yaml --wallet ../ignore --silent | grep -A2 'Version info' | sed "s/Version info:/ZBox Version Info:/") || true
+
+    - name: "Stake blobbers using above built binaries"
+      shell: 'script --return --quiet --command "bash {0}"'
+      run: |
+        echo '#!/bin/bash
+        echo
+        echo "==========================================================="
+        echo "STAKING BLOBBERS USING ZWALLETCLI & ZBOXCLI BINARIES"
+        echo "==========================================================="
+        echo
+        cd tests/cli_tests
+        ./zwallet register --silent > build.log 2>&1 || { cat build.log && echo "::error title=Failed to stake the blobbers::failed to register wallet through zwalletCLI built using above branch and goSDK." && exit 1; }
+        for i in {1..6}
+        do
+        ./zwallet faucet --methodName "pour" --input "{}" --tokens 2 --silent > build.log 2>&1 || { cat build.log && echo "::error title=Failed to stake the blobbers::failed to execute faucet through zwalletCLI built using above branch and goSDK." && exit 1; }
+        done
+
+        blobber_ids=( $(./zwallet getblobbers --silent | grep -o '[a-z0-9]\{64\}') )
+        for id in "${blobber_ids[@]}"
+        do
+          ./zbox sp-lock --blobber_id $id --tokens 2 --silent > build.log 2>&1 || { cat build.log && echo "::error title=Failed to stake the blobbers::failed to use sp-lock in zwalletCLI built using above branch and goSDK." && exit 1; }
+        done
+        ' > ./stake_blobbers.sh;
+        chmod 777 ./stake_blobbers.sh;
+        ./stake_blobbers.sh
 
     - name: "Run CLI System Tests"
       shell: 'script --return --quiet --command "bash {0}"'
