add error annotation

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -247,14 +247,14 @@ runs:
 
         if [ "$?" == "1" ];
           then
-            echo "FILES IN FILTER COULD NOT BE FOUND" && exit 1
+            echo "::error title=Test files do not exist!::Test files in filter [$testFiles] could not be found" && exit 1
         fi
 
         testFunctions=$(grep -o '^[^\/]*func Test.*' $(echo $testFiles) | sed 's/^[^/]*func \(Test[A-Za-z0-9_]*\).*$/\1/' | paste -sd "|" -)
 
         if [ -z "$testFunctions" ];
           then
-            echo "NO TEST FUNCTIONS FOUND IN FILE" && exit 1
+            echo "::error title=Test functions not found!::Test files in filter [$testFiles] do not contain test functions" && exit 1
         fi
 
         printf '#!/bin/bash\nset -o pipefail\nCONFIG_PATH=./zbox_config.yaml go test -timeout=60m -run  "'$testFunctions'" ./... -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > SUBSET_TEST_RUNNER_COMMAND.sh && chmod 777 SUBSET_TEST_RUNNER_COMMAND.sh
