Monitor chain tests

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -58,6 +58,10 @@ inputs:
     required: false
     default: "true"
     description: 'Enable or disable S3 migration CLI system tests'
+  run_monitoring_system_tests:
+    required: false
+    default: "true"
+    description: 'Enable or disable monitoring system tests'
   run_api_system_tests:
     required: false
     default: "true"
@@ -210,6 +214,13 @@ runs:
           else
             echo RUN_CHIMNEY_BLOBBER_TESTS=true >> $GITHUB_ENV
         fi
+        
+        if [ "${{ inputs.run_monitoring_system_tests }}" == "false" ];
+          then
+            echo RUN_MONITORING_SYSTEM_TESTS=false >> $GITHUB_ENV
+          else
+            echo RUN_MONITORING_SYSTEM_TESTS=true >> $GITHUB_ENV
+        fi
 
     - name: "VIEW TEST CONFIGURATION"
       shell: 'script --return --quiet --command "bash {0}"'
@@ -229,6 +240,8 @@ runs:
         echo "Custom gosdk version:          [${{ env.GOSDK_VERSION }}]"
         echo "Test file filter:              [${{ inputs.test_file_filter }}]"
         echo "Running CLI tests:             [${{ env.RUN_CLI_SYSTEM_TESTS }}]"
+        echo "Running S3 CLI tests:          [${{ env.RUN_S3_CLI_SYSTEM_TESTS }}]"
+        echo "Running Monitoring tests:      [${{ env.RUN_MONITORING_SYSTEM_TESTS }}]"
         echo "Running API tests:             [${{ env.RUN_API_SYSTEM_TESTS }}]"
         echo "Running Tokenomics tests:      [${{ env.RUN_TOKENOMICS_SYSTEM_TESTS }}]"
         echo "Running Chimney Blobber tests: [${{ env.RUN_CHIMNEY_BLOBBER_TESTS }}]"
@@ -411,6 +424,7 @@ runs:
         printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^Test0S3[^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./zbox_config.yaml go test -timeout=20m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > S3CLI_TEST_RUNNER_COMMAND.sh && chmod 777 S3CLI_TEST_RUNNER_COMMAND.sh
         printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^TestProtocolChallengeTimings[^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./config/api_tests_config.yaml go test -timeout=30m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > CHALLENGE_API_TEST_RUNNER_COMMAND.sh && chmod 777 CHALLENGE_API_TEST_RUNNER_COMMAND.sh
         printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^TestProtocolChallenge[^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./zbox_config.yaml go test -timeout=120m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > CHALLENGE_TEST_RUNNER_COMMAND.sh && chmod 777 CHALLENGE_TEST_RUNNER_COMMAND.sh
+        printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^TestMonitoring[^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./zbox_config.yaml go test -timeout=120m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > MONITORING_TEST_RUNNER_COMMAND.sh && chmod 777 MONITORING_TEST_RUNNER_COMMAND.sh
         printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^TestKill[^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./zbox_config.yaml go test -timeout=120m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > KILL_TEST_RUNNER_COMMAND.sh && chmod 777 KILL_TEST_RUNNER_COMMAND.sh
         printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^Test[^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./config/tokenomics_tests_config.yaml go test -timeout=120m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > TOKENOMICS_TEST_RUNNER_COMMAND.sh && chmod 777 TOKENOMICS_TEST_RUNNER_COMMAND.sh
         printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^Test1ChimneyBlobberRewards$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./config/api_tests_config.yaml go test -timeout=90m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > CHIMNEY_BLOBBER_TEST_RUNNER_COMMAND.sh && chmod 777 CHIMNEY_BLOBBER_TEST_RUNNER_COMMAND.sh
@@ -891,6 +905,50 @@ runs:
           ./tests/cli_tests/cmdlog.log
           ./${{ env.BRANCH_DIR }}/latest/cli/index.html
           ./${{ env.BRANCH_DIR }}/latest/killtestscli/index.html
+
+    - name: "Run Monitoring System Tests"
+      shell: 'script --return --quiet --command "bash {0}"'
+      if: ${{ always() && env.TESTS_READY && env.RUN_MONITORING_SYSTEM_TESTS == 'true' && env.RUN_SUBSET_OF_TESTS == 'false' }}
+      run: |
+          echo
+          echo "======================================================"
+          echo "RUNNING MONITORING SYSTEM TESTS:"
+          echo "======================================================"
+          echo
+  
+          export HOME="/root"
+          GOPATH=$(echo $(go env GOPATH))
+  
+          cd tests/monitoring_tests
+          monitoring_system_tests_exit_code=0
+          ${GOPATH}/bin/gotestsum --jsonfile test-output.json --hide-summary=output --format testname ${{ env.SHOULD_RETRY_FAILURES }} --raw-command -- ../../MONITORING_TEST_RUNNER_COMMAND.sh || monitoring_system_tests_exit_code=$?
+          cat test-output.json | ${GOPATH}/bin/go-test-report --groupSize 1 --output ../../${{ env.BRANCH_DIR }}/${GITHUB_SHA}/monitoring/index.html --title "0Chain Monitoring System test suite [${{ env.BRANCH_DIR }}/${GITHUB_SHA:0:8}] ran against [${{ env.NETWORK_URL }}] at [${{ env.TEST_TIME }}]"
+  
+          cp -R ../../${{ env.BRANCH_DIR }}/${GITHUB_SHA}/monitoring ../../${{ env.BRANCH_DIR }}/latest/
+          echo "MONITORING_TESTS_RAN=true" >> $GITHUB_ENV
+  
+          if [[ $monitoring_system_tests_exit_code == 0 ]];
+              then
+              echo MONITORING_TESTS_PASSED=true >> $GITHUB_ENV
+              else
+              echo MONITORING_TESTS_PASSED=false >> $GITHUB_ENV
+              echo "::error title=Monitoring System tests faled!::Monitoring System tests failed. Ensure tests are running against the correct images/branches and rule out any possible code issues before attempting a re-run"
+          fi
+  
+          exit $monitoring_system_tests_exit_code
+
+    - name: "Archive Monitoring Test Config & Console Output"
+      continue-on-error: true
+      if: ${{ always() && env.RUN_MONITORING_SYSTEM_TESTS == 'true' && env.RUN_SUBSET_OF_TESTS == 'false' }}
+      uses: actions/upload-artifact@v3
+      with:
+          name: Monitoring-System-Test-${{ env.TEST_TIME }}
+          path: |
+            ./tests/monitoring_tests/config
+            ./${{ env.BRANCH_DIR }}/latest/monitoring/index.html
+        
+        
+        
 
     - name: "Run Tokenomics System Tests"
       shell: 'script --return --quiet --command "bash {0}"'
