improve logging

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -242,21 +242,23 @@ runs:
         cd tests/cli_tests
 
         testFiles=$(echo ${{ inputs.test_file_filter }} | sed 's/,/ /g')
+        echo "Attempting to resolve filter to test files..."
         ls $(echo $testFiles)
 
         fileListResult="$?"
-        echo "fileListResult=$fileListResult"
 
         if [ "$fileListResult" != "0" ];
           then
-            echo "::error title=Test files do not exist!::Test files in filter [$testFiles] could not be found" && exit 1
+            echo "::error title=Test files do not exist!::One or more of the test files requested [$testFiles] could not be found" && exit 1
+          else
+            echo "SUCCESS!"
         fi
 
         testFunctions=$(grep -o '^[^\/]*func Test.*' $(echo $testFiles) | sed 's/^[^/]*func \(Test[A-Za-z0-9_]*\).*$/\1/' | paste -sd "|" -)
 
         if [ -z "$testFunctions" ];
           then
-            echo "::error title=Test functions not found!::Test files in filter [$testFiles] do not contain test functions" && exit 1
+            echo "::error title=Test functions not found!::No test functions found in any of the test files requested [$testFiles]" && exit 1
         fi
 
         printf '#!/bin/bash\nset -o pipefail\nCONFIG_PATH=./zbox_config.yaml go test -timeout=60m -run  "'$testFunctions'" ./... -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > SUBSET_TEST_RUNNER_COMMAND.sh && chmod 777 SUBSET_TEST_RUNNER_COMMAND.sh
