wait for apt lock before attempting to install dependencies

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -79,35 +79,7 @@ runs:
         repository: "0chain/system_test"
         ref: ${{ env.SYSTEM_TESTS_BRANCH }}
 
-
-#    - name: "Get CLI Cache Key"
-#      shell: 'script --return --quiet --command "bash {0}"'
-#      run: |
-#        if [[ '${{ env.ZWALLET_BRANCH }}' =~ ^[a-f0-9]{40}$ ]];
-#          then
-#            echo ZWALLET_SHA=${{ env.ZWALLET_BRANCH }} >> $GITHUB_ENV
-#          else
-#           echo ZWALLET_SHA=$(curl --silent --fail https://api.github.com/repos/0chain/zwalletcli/git/refs/heads/${{ env.ZWALLET_BRANCH }} | jq --raw-output .object.sha) >> $GITHUB_ENV
-#        fi
-#
-#        if [[ '${{ env.ZBOX_BRANCH }}' =~ ^[a-f0-9]{40}$ ]];
-#          then
-#            echo ZBOX_SHA=${{ env.ZBOX_BRANCH }} >> $GITHUB_ENV
-#          else
-#           echo ZBOX_SHA=$(curl --silent --fail https://api.github.com/repos/0chain/zboxcli/git/refs/heads/${{ env.ZBOX_BRANCH }} | jq --raw-output .object.sha) >> $GITHUB_ENV
-#        fi
-#
-#    - name: "Cache CLI Binaries"
-#      id: cli-cache
-#      uses: actions/cache@v2
-#      with:
-#        path: |
-#          tests/cli_tests/zbox
-#          tests/cli_tests/zwallet
-#        key: cli-cache-${{ runner.os }}-${{ env.ZWALLET_SHA }}-${{ env.ZBOX_SHA }}-v3
-
     - name: "Checkout 0wallet CLI"
-#      if: steps.cli-cache.outputs.cache-hit != 'true'
       uses: actions/checkout@v2
       with:
         ref: ${{ env.ZWALLET_BRANCH }}
@@ -116,7 +88,6 @@ runs:
         path: ./zwalletcli
 
     - name: "Checkout 0box CLI"
-#      if: steps.cli-cache.outputs.cache-hit != 'true'
       uses: actions/checkout@v2
       with:
         ref: ${{ env.ZBOX_BRANCH }}
@@ -141,12 +112,11 @@ runs:
         sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl > build.log 2>&1 || { cat build.log && echo "::error title=Failed to install test dependency::failed to install youtube-dl" && exit 1; }
         sudo chmod a+rx /usr/local/bin/youtube-dl
         echo "installing ffmpeg..."
-        sudo apt update > build.log 2>&1 || { cat build.log && exit 1; }
-        sudo apt install -y ffmpeg > build.log 2>&1 || { cat build.log && echo "::error title=Failed to install test dependency::failed to install ffmpeg" && exit 1; }
+        timeout 60 (sudo aptdcon --refresh > build.log 2>&1 || { cat build.log && exit 1; })
+        timeout 60 (yes | sudo aptdcon --hide-terminal --install ffmpeg > build.log 2>&1 || { cat build.log && echo "::error title=Failed to install test dependency::failed to install ffmpeg" && exit 1; })
         echo "Test dependencies install SUCCESS!"
 
     - name: "Build CLI Binaries"
-#      if: steps.cli-cache.outputs.cache-hit != 'true'
       shell: 'script --return --quiet --command "bash {0}"'
       run: |
         echo
