use correct variable

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -297,7 +297,7 @@ runs:
         echo '#!/bin/bash
         cd $2
         echo "Upgrading [$3] to GOSDK [${{ env.GOSDK_VERSION }}/$1]"
-        go get github.com/0chain/gosdk@$GOSDK_HEAD || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ env.GOSDK_VERSION }}]" && exit 1; }
+        go get github.com/0chain/gosdk@$1 || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ env.GOSDK_VERSION }}]" && exit 1; }
         go mod tidy || { echo "::error title=Failed to upgrade $3 gosdk::failed to upgrade $3 gosdk to [${{ env.GOSDK_VERSION }}]" && exit 1; }
         cd -
         ' > ./upgrade-gosdk.sh;
