allow overriding of snapshots image

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -12,17 +12,17 @@ inputs:
     required: true
     description: 'Network to run system tests against INSTEAD OF DEPLOYING A NEW NETWORK. [example: dev.0chain.net]'
   zbox_cli_branch:
-    required: true
+    required: false
     description: '0Box CLI (branch or commit SHA) which the tests will use'
-    default: 'staging'
+    default: ''
   zwallet_cli_branch:
-    required: true
+    required: false
     description: '0Wallet CLI (branch or commit SHA) which the tests will use'
-    default: 'staging'
+    default: ''
   s3_migration_cli_branch:
     required: false
     description: 'S3 Migration CLI (branch or commit SHA) which the tests will use'
-    default: 'staging'
+    default: ''
   deploy_report_page:
     required: true
     default: "true"
@@ -101,29 +101,25 @@ runs:
       shell: 'script --return --quiet --command "bash {0}"'
       run: |
         
-        if [[ -z "$SPRINT_BRANCH_ZBOXCLI" ]];then
-            echo "ZBOX_BRANCH=$(echo ${{inputs.zbox_cli_branch}})" >> $GITHUB_ENV
-        else
-            echo "ZBOX_BRANCH=$(echo $SPRINT_BRANCH_ZBOXCLI)" >> $GITHUB_ENV
+        echo '#!/bin/bash
+        if [[ -z "$1" ]];then
+           if [[ -z "$2" ]];then
+             echo "::error title=Image not specified!::$3 was not specified explicitly or in repo_snapshots_branch"
+           else
+             echo "${3}=$(echo '$2')" >> $GITHUB_ENV
+           fi
         fi
+        else
+           echo "Using $3 tag [$1] from repo_snapshots_branch"
+           echo "${3}=$(echo '$1')" >> $GITHUB_ENV
+        fi
+        ' > ./check-params.sh;
+        chmod 777 check-params.sh
         
-        if [[ -z "$SPRINT_BRANCH_ZWALLETCLI" ]];then
-            echo "ZWALLET_BRANCH=$(echo ${{inputs.zwallet_cli_branch}})" >> $GITHUB_ENV
-        else
-            echo "ZWALLET_BRANCH=$(echo $SPRINT_BRANCH_ZWALLETCLI)" >> $GITHUB_ENV
-        fi
-        
-        if [[ -z "$SPRINT_BRANCH_SYSTEM_TESTS" ]];then
-            echo "SYSTEM_TESTS_BRANCH=$(echo $(([ -z '${{inputs.system_tests_branch}}' ] && echo  ${GITHUB_REF#refs/*/}) || echo '${{inputs.system_tests_branch}}'))" >> $GITHUB_ENV
-        else
-            echo "SYSTEM_TESTS_BRANCH=$(echo $SPRINT_BRANCH_SYSTEM_TESTS)" >> $GITHUB_ENV
-        fi
-        
-        if [[ -z "$SPRINT_BRANCH_S3_MIGRATION" ]];then
-             echo "S3_MIGRATION_BRANCH=$(echo ${{inputs.s3_migration_cli_branch}})" >> $GITHUB_ENV
-        else
-            echo "S3_MIGRATION_BRANCH=$(echo $SPRINT_BRANCH_S3_MIGRATION)" >> $GITHUB_ENV
-        fi
+        ./check-params.sh "${{inputs.zbox_cli_branch}}" "${{ env.SPRINT_BRANCH_ZBOXCLI" }}" "ZBOX_BRANCH"
+        ./check-params.sh "${{inputs.zwallet_cli_branch}}" "${{ env.SPRINT_BRANCH_ZWALLETCLI" }}" "ZWALLET_BRANCH"
+        ./check-params.sh "$(echo $(([ -z '${{inputs.system_tests_branch}}' ] && echo  ${GITHUB_REF#refs/*/}) || echo '${{inputs.system_tests_branch}}'))" "${{ env.SPRINT_BRANCH_SYSTEM_TESTS" }}" "SYSTEM_TESTS_BRANCH"
+        ./check-params.sh  "${{inputs.s3_migration_cli_branch}}" "${{ env.SPRINT_BRANCH_S3_MIGRATION" }}" "S3_MIGRATION_BRANCH"
         
         echo "NETWORK_URL=$(echo ${{ inputs.network }})" >> $GITHUB_ENV
         echo "GOMODCACHE=/root/actions-runner${RUNNER_NAME:(-1)}/_work/_tool/go/pkg/mod" >> $GITHUB_ENV
