don't archive logs if network was not deployed as part of test run

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -112,8 +112,8 @@ runs:
         sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl > build.log 2>&1 || { cat build.log && echo "::error title=Failed to install test dependency::failed to install youtube-dl" && exit 1; }
         sudo chmod a+rx /usr/local/bin/youtube-dl
         echo "installing ffmpeg..."
-        timeout 60 (sudo aptdcon --refresh > build.log 2>&1 || { cat build.log && exit 1; })
-        timeout 60 (yes | sudo aptdcon --hide-terminal --install ffmpeg > build.log 2>&1 || { cat build.log && echo "::error title=Failed to install test dependency::failed to install ffmpeg" && exit 1; })
+        timeout 60 ( sudo aptdcon --refresh > build.log 2>&1 || { cat build.log && exit 1; } )
+        timeout 60 ( yes | sudo aptdcon --hide-terminal --install ffmpeg > build.log 2>&1 || { cat build.log && echo "::error title=Failed to install test dependency::failed to install ffmpeg" && exit 1; } )
         echo "Test dependencies install SUCCESS!"
 
     - name: "Build CLI Binaries"
@@ -388,40 +388,42 @@ runs:
         echo "======================================================"
         echo "Extracting Logging From Pods:"
         echo "======================================================"
-       
 
-        echo '#!/bin/bash
-        app=$1
-        output=$2
+        if [ -n "${{ env.NAMESPACE }}" ]; then
+          echo '#!/bin/bash
+          app=$1
+          output=$2
 
-      
-        podname=$(kubectl -n ${{ env.NAMESPACE }} --kubeconfig ../kube/${{ env.NAMESPACE }}-config get pods --no-headers -l app=$app -o custom-columns=:metadata.name)
-        
-        kubectl -n ${{ env.NAMESPACE }} --kubeconfig ../kube/${{ env.NAMESPACE }}-config cp $podname:log $output && echo "OK" | grep -v tar
-        ' > ./logging.sh
+          podname=$(kubectl -n ${{ env.NAMESPACE }} --kubeconfig ../kube/${{ env.NAMESPACE }}-config get pods --no-headers -l app=$app -o custom-columns=:metadata.name)
 
-        chmod 777 ./logging.sh;
+          kubectl -n ${{ env.NAMESPACE }} --kubeconfig ../kube/${{ env.NAMESPACE }}-config cp $podname:log $output && echo "OK" | grep -v tar
+          ' > ./logging.sh
 
-        echo -ne " [+] sharder-01 " && ./logging.sh 0chain-sharder-01 ./logs/sharder-01
-        echo -ne " [+] sharder-02 " && ./logging.sh 0chain-sharder-02 ./logs/sharder-02
-        echo 
-        echo -ne " [+] miner-01 " && ./logging.sh 0chain-miner-01 ./logs/miner-01
-        echo -ne " [+] miner-01 " && ./logging.sh 0chain-miner-02 ./logs/miner-02
-        echo -ne " [+] miner-01 " && ./logging.sh 0chain-miner-03 ./logs/miner-03
-        echo
-        echo -ne " [+] blobber-01 " && ./logging.sh blobber-blobber-01 ./logs/blobber-01
-        echo -ne " [+] blobber-02 " && ./logging.sh blobber-blobber-02 ./logs/blobber-02
-        echo -ne " [+] blobber-03 " && ./logging.sh blobber-blobber-03 ./logs/blobber-03
-        echo -ne " [+] blobber-04 " && ./logging.sh blobber-blobber-04 ./logs/blobber-04
-        echo -ne " [+] blobber-05 " && ./logging.sh blobber-blobber-05 ./logs/blobber-05
-        echo -ne " [+] blobber-06 " && ./logging.sh blobber-blobber-06 ./logs/blobber-06
-        echo
-        echo -ne " [+] validator-01 " && ./logging.sh blobber-validator-01 ./logs/validator-01
-        echo -ne " [+] validator-02 " && ./logging.sh blobber-validator-02 ./logs/validator-02
-        echo -ne " [+] validator-03 " && ./logging.sh blobber-validator-03 ./logs/validator-03
-        echo -ne " [+] validator-04 " && ./logging.sh blobber-validator-04 ./logs/validator-04
-        echo -ne " [+] validator-05 " && ./logging.sh blobber-validator-05 ./logs/validator-05
-        echo -ne " [+] validator-06 " && ./logging.sh blobber-validator-06 ./logs/validator-06
+          chmod 777 ./logging.sh;
+
+          echo -ne " [+] sharder-01 " && ./logging.sh 0chain-sharder-01 ./logs/sharder-01
+          echo -ne " [+] sharder-02 " && ./logging.sh 0chain-sharder-02 ./logs/sharder-02
+          echo
+          echo -ne " [+] miner-01 " && ./logging.sh 0chain-miner-01 ./logs/miner-01
+          echo -ne " [+] miner-01 " && ./logging.sh 0chain-miner-02 ./logs/miner-02
+          echo -ne " [+] miner-01 " && ./logging.sh 0chain-miner-03 ./logs/miner-03
+          echo
+          echo -ne " [+] blobber-01 " && ./logging.sh blobber-blobber-01 ./logs/blobber-01
+          echo -ne " [+] blobber-02 " && ./logging.sh blobber-blobber-02 ./logs/blobber-02
+          echo -ne " [+] blobber-03 " && ./logging.sh blobber-blobber-03 ./logs/blobber-03
+          echo -ne " [+] blobber-04 " && ./logging.sh blobber-blobber-04 ./logs/blobber-04
+          echo -ne " [+] blobber-05 " && ./logging.sh blobber-blobber-05 ./logs/blobber-05
+          echo -ne " [+] blobber-06 " && ./logging.sh blobber-blobber-06 ./logs/blobber-06
+          echo
+          echo -ne " [+] validator-01 " && ./logging.sh blobber-validator-01 ./logs/validator-01
+          echo -ne " [+] validator-02 " && ./logging.sh blobber-validator-02 ./logs/validator-02
+          echo -ne " [+] validator-03 " && ./logging.sh blobber-validator-03 ./logs/validator-03
+          echo -ne " [+] validator-04 " && ./logging.sh blobber-validator-04 ./logs/validator-04
+          echo -ne " [+] validator-05 " && ./logging.sh blobber-validator-05 ./logs/validator-05
+          echo -ne " [+] validator-06 " && ./logging.sh blobber-validator-06 ./logs/validator-06
+        else
+          echo "NOT archiving logs because network was not deployed as part of this test run"
+        fi
 
     - name: "Archive Sharder Logging"
       if: ${{ failure() }}
