add chimney blobber tests (#270)
* add chimney blobber tests

* fix report output

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -78,6 +78,10 @@ inputs:
     required: false
     default: "false"
     description: 'Run subset of system tests (smoke tests)'
+  run_chimney_blobber_tests:
+    required: false
+    default: "false"
+    description: 'Run chimney blobber tests'
   TENDERLY_FORK_ID:
     required: true
     description: 'Tenderly fork ID is used to use Tenderly fork simulations for bridge tests'
@@ -202,6 +206,13 @@ runs:
             echo RUN_TOKENOMICS_SYSTEM_TESTS=true >> $GITHUB_ENV
         fi
 
+        if [ "${{ inputs.run_chimney_blobber_tests }}" == "false" ];
+          then
+            echo RUN_CHIMNEY_BLOBBER_TESTS=false >> $GITHUB_ENV
+          else
+            echo RUN_CHIMNEY_BLOBBER_TESTS=true >> $GITHUB_ENV
+        fi
+
     - name: "VIEW TEST CONFIGURATION"
       shell: 'script --return --quiet --command "bash {0}"'
       run: |
@@ -209,21 +220,22 @@ runs:
         echo "======================================================"
         echo "RUNNING SYSTEM TESTS WITH THE FOLLOWING CONFIGURATION:"
         echo "======================================================"
-        echo "System tests branch:      [${{ env.SYSTEM_TESTS_BRANCH }}]"
-        echo "repo-snapshots branch:    [${{ env.REPO_SNAPSHOTS_BRANCH }}]"
-        echo "0Chain network URL:       [${{ env.NETWORK_URL }}]"
-        echo "0box network URL:         [0box.${{ env.NETWORK_URL }}]"
-        echo "0box CLI branch:          [${{ env.ZBOX_BRANCH }}]"
-        echo "0wallet CLI branch:       [${{ env.ZWALLET_BRANCH }}]"
-        echo "s3 migration CLI branch:  [${{ env.S3_MIGRATION_BRANCH }}]"
-        echo "Ethereum node URL:        [https://rpc.tenderly.co/fork/${{ inputs.TENDERLY_FORK_ID }}]"
-        echo "Custom gosdk version:     [${{ env.GOSDK_VERSION }}]"
-        echo "Test file filter:         [${{ inputs.test_file_filter }}]"
-        echo "Running CLI tests:        [${{ env.RUN_CLI_SYSTEM_TESTS }}]"
-        echo "Running API tests:        [${{ env.RUN_API_SYSTEM_TESTS }}]"
-        echo "Running Tokenomics tests: [${{ env.RUN_TOKENOMICS_SYSTEM_TESTS }}]"
-        echo "Running smoke tests:      [${{ env.RUN_SMOKE_TESTS }}]"
-        echo "Running frontend tests:   [${{ env.RUN_FRONTEND_TESTS }}]"
+        echo "System tests branch:           [${{ env.SYSTEM_TESTS_BRANCH }}]"
+        echo "repo-snapshots branch:         [${{ env.REPO_SNAPSHOTS_BRANCH }}]"
+        echo "0Chain network URL:            [${{ env.NETWORK_URL }}]"
+        echo "0box network URL:              [0box.${{ env.NETWORK_URL }}]"
+        echo "0box CLI branch:               [${{ env.ZBOX_BRANCH }}]"
+        echo "0wallet CLI branch:            [${{ env.ZWALLET_BRANCH }}]"
+        echo "s3 migration CLI branch:       [${{ env.S3_MIGRATION_BRANCH }}]"
+        echo "Ethereum node URL:             [https://rpc.tenderly.co/fork/${{ inputs.TENDERLY_FORK_ID }}]"
+        echo "Custom gosdk version:          [${{ env.GOSDK_VERSION }}]"
+        echo "Test file filter:              [${{ inputs.test_file_filter }}]"
+        echo "Running CLI tests:             [${{ env.RUN_CLI_SYSTEM_TESTS }}]"
+        echo "Running API tests:             [${{ env.RUN_API_SYSTEM_TESTS }}]"
+        echo "Running Tokenomics tests:      [${{ env.RUN_TOKENOMICS_SYSTEM_TESTS }}]"
+        echo "Running Chimney Blobber tests: [${{ env.RUN_CHIMNEY_BLOBBER_TESTS }}]"
+        echo "Running smoke tests:           [${{ env.RUN_SMOKE_TESTS }}]"
+        echo "Running frontend tests:        [${{ env.RUN_FRONTEND_TESTS }}]"
 
     - name: "Checkout System Tests"
       uses: actions/checkout@v3
@@ -380,12 +392,13 @@ runs:
         sed "s,s3_secret_key:.*,s3_secret_key: ${{ inputs.S3_SECRET_KEY }}," -i ./tests/cli_tests/config/cli_tests_config.yaml
         
 
-        printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^Test[^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./config/api_tests_config.yaml go test -timeout=30m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > API_TEST_RUNNER_COMMAND.sh && chmod 777 API_TEST_RUNNER_COMMAND.sh
+        printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^Test[^___][^ChimneyBlobberRewards]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./config/api_tests_config.yaml go test -timeout=30m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > API_TEST_RUNNER_COMMAND.sh && chmod 777 API_TEST_RUNNER_COMMAND.sh
         printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^Test[^K0P][^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./zbox_config.yaml go test -timeout=120m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > TEST_RUNNER_COMMAND.sh && chmod 777 TEST_RUNNER_COMMAND.sh
         printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^Test0S3[^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./zbox_config.yaml go test -timeout=20m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > S3CLI_TEST_RUNNER_COMMAND.sh && chmod 777 S3CLI_TEST_RUNNER_COMMAND.sh
         printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^TestProtocolChallenge[^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./zbox_config.yaml go test -timeout=120m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > CHALLENGE_TEST_RUNNER_COMMAND.sh && chmod 777 CHALLENGE_TEST_RUNNER_COMMAND.sh
         printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^TestKill[^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./zbox_config.yaml go test -timeout=120m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > KILL_TEST_RUNNER_COMMAND.sh && chmod 777 KILL_TEST_RUNNER_COMMAND.sh
         printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^Test[^___]*$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./config/tokenomics_tests_config.yaml go test -timeout=120m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > TOKENOMICS_TEST_RUNNER_COMMAND.sh && chmod 777 TOKENOMICS_TEST_RUNNER_COMMAND.sh
+        printf '#!/bin/bash\nset -o pipefail\n[ -z "$1" ] && TESTS_TO_RUN="-run  ^TestChimneyBlobberRewards$ ./..." || TESTS_TO_RUN=$1\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./config/api_tests_config.yaml go test -timeout=30m $TESTS_TO_RUN -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > CHIMNEY_BLOBBER_TEST_RUNNER_COMMAND.sh && chmod 777 CHIMNEY_BLOBBER_TEST_RUNNER_COMMAND.sh
         printf '#!/bin/bash\nset -o pipefail\nSMOKE_TEST_MODE=${{ env.RUN_SMOKE_TESTS }} CONFIG_PATH=./zbox_config.yaml go test -timeout=60m -run  "^Test___Flaky.*$" ./... -json -count=1 | sed -r "/(=== (CONT|RUN|PAUSE).*)|(--- FAIL:.*)|(\\"Test\\":\\".*\/[pP]arallel\\")/d"' > FLAKY_TEST_RUNNER_COMMAND.sh && chmod 777 FLAKY_TEST_RUNNER_COMMAND.sh
 
         mkdir -p ${BRANCH_DIR}/${GITHUB_SHA}/api
@@ -888,6 +901,43 @@ runs:
         path: |
           ./tests/tokenomics_tests/config
           ./${{ env.BRANCH_DIR }}/latest/tokenomics/index.html
+
+    - name: "Run Chimney Blobber System Tests"
+      shell: 'script --return --quiet --command "bash {0}"'
+      if:  ${{ always() && env.TESTS_READY && env.RUN_CHIMNEY_BLOBBER_TESTS == 'true' && env.RUN_SUBSET_OF_TESTS == 'false' }}
+      run: |
+        echo
+        echo "======================================================"
+        echo "RUNNING Chimney Blobber SYSTEM TESTS:"
+        echo "======================================================"
+        echo
+        export HOME="/root"
+        cd tests/api_tests
+        chimney_blobber_tests_exit_code=0
+        GOPATH=$(echo $(go env GOPATH))
+        ${GOPATH}/bin/gotestsum --jsonfile test-output.json --hide-summary=output --format testname ${{ env.SHOULD_RETRY_FAILURES }} --raw-command -- ../../CHIMNEY_BLOBBER_TEST_RUNNER_COMMAND.sh || chimney_blobber_tests_exit_code=$?
+        cat test-output.json | ${GOPATH}/bin/go-test-report --groupSize 1 --output ../../${{ env.BRANCH_DIR }}/${GITHUB_SHA}/api/chimney_blobber_index.html --title "0Chain Chimney Blobber System test suite [${{ env.BRANCH_DIR }}/${GITHUB_SHA:0:8}] ran against [${{ env.NETWORK_URL }}] at [${{ env.TEST_TIME }}]"
+
+        cp -R ../../${{ env.BRANCH_DIR }}/${GITHUB_SHA}/api ../../${{ env.BRANCH_DIR }}/latest/
+        if [[ $chimney_blobber_tests_exit_code == 0 ]];
+          then
+            echo CHIMNEY_BLOBBER_TESTS_PASSED=true >> $GITHUB_ENV
+          else
+            echo CHIMNEY_BLOBBER_TESTS_PASSED=false >> $GITHUB_ENV
+            echo "::error title=Chimney Blobber System tests faled!::Chimney Blobber System tests failed. Ensure tests are running against the correct images/branches and rule out any possible code issues before attempting a re-run"
+        fi
+
+        exit $chimney_blobber_tests_exit_code
+
+    - name: "Archive Chimney Blobber Test Config & Console Output"
+      continue-on-error: true
+      if: ${{ always() && env.RUN_CHIMNEY_BLOBBER_TESTS == 'true' && env.RUN_SUBSET_OF_TESTS == 'false' }}
+      uses: actions/upload-artifact@v3
+      with:
+        name: Chimney-Blobber-Test-${{ env.TEST_TIME }}
+        path: |
+          ./tests/api_tests/config
+          ./${{ env.BRANCH_DIR }}/latest/api_tests/chimney_blobber_index.html
 
     - name: "System Stability Check"
       if: ${{ always() && (env.TESTS_RAN == 'true' || env.API_TESTS_RAN == 'true') }}
