updated for mc, warp,  minio cli

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -356,7 +356,26 @@ runs:
         cd ../s3-migration
         make build > build.log 2>&1 || { cat build.log && echo "::error title=s3 migration CLI build failed::s3 migration CLI build failed" && exit 1; }
         mv s3mgrt ../tests/cli_tests
+
+        echo "Building mc CLI staging branch...."
+        git clone https://github.com/0chain/mc.git staging
+        cd mc
+        make install > build.log 2>&1 || { cat build.log && echo "::error title=mc CLI build failed::mc CLI build failed" && exit 1; }
+        mv mc ../tests/cli_tests
+
+        echo "Building minio CLI master branch...."
+        git clone https://github.com/minio/minio.git master
+        cd minio
+        make install > build.log 2>&1 || { cat build.log && echo "::error title=minio CLI build failed::minio CLI build failed" && exit 1; }
+        mv minio ../tests/cli_tests
         
+
+        echo "Building warp CLI master branch...."
+        git clone https://github.com/minio/warp.git master
+        cd warp
+        make install > build.log 2>&1 || { cat build.log && echo "::error title=warp CLI build failed::warp CLI build failed" && exit 1; }
+        mv warp ../tests/cli_tests
+
         echo "CLI build SUCCESS!"
 
     - name: "Set up system tests"
