add retries

diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -207,7 +207,6 @@ runs:
         echo "==========================================================="
         echo
         cd tests/cli_tests
-        cat ./config/blobber_stake_wallet.json
         ./zwallet register --configDir ./config --config ./zbox_config.yaml --wallet ../ignore > build.log 2>&1 || { cat build.log && echo "::error title=Failed to stake the blobbers::failed to register wallet through zwalletCLI built using above branch and goSDK." && exit 1; }
         for i in {1..6}
         do
@@ -219,10 +218,26 @@ runs:
         do
           ./zbox sp-lock --blobber_id $id --tokens 1 --configDir ./config --config ./zbox_config.yaml --wallet ../ignore > build.log 2>&1 || { cat build.log && echo "::error title=Failed to stake the blobbers::failed to use sp-lock in zwalletCLI built using above branch and goSDK." && exit 1; }
         done
-        echo "Stake blobbers successfully..."
         ' > ./stake_blobbers.sh;
         chmod 777 ./stake_blobbers.sh;
-        ./stake_blobbers.sh
+
+        ITER=0
+        MAX_RETRIES=3
+        until [[ $ITER -eq $MAX_RETRIES ]]
+        do
+            ./stake_blobbers.sh && break
+            ITER=$((ITER+1))
+            echo "Staking blobbers failed on try $ITER. Retrying in 5 seconds..."
+            sleep 5
+        done
+
+        if [[ $ITER -eq $MAX_RETRIES ]]
+          then
+            echo "Staking blobbers failed after $MAX_RETRIES tries. Exiting run..."
+            exit 1
+          else
+            echo "Blobbers staked succefully on try $((ITER+1)). Moving on to tests..."
+        fi
 
     - name: "Run CLI System Tests"
       shell: 'script --return --quiet --command "bash {0}"'
