Use git head sha for gosdk upgrade instead of branch name

diff --git a/deploy-0chain/action.yml b/deploy-0chain/action.yml
--- a/deploy-0chain/action.yml
+++ b/deploy-0chain/action.yml
@@ -468,6 +468,31 @@ runs:
         fetch-depth: 1
         path: ./zboxcli
 
+    - name: "Upgrade GoSDK"
+      shell: 'script --return --quiet --command "bash {0}"'
+      if: ${{ env.GOSDK_VERSION != '' && env.GOSDK_VERSION == 'NONE' }}
+      run: |
+        echo
+        echo "=============================================================="
+        echo "UPGRADING GOSDK IN ZBOXCLI, ZWALLETCLI"
+        echo "=============================================================="
+        echo
+
+        GOSDK_HEAD=$(curl -s -H "Authorization: token ${{ inputs.svc_account_secret }}" https://api.github.com/repos/0chain/gosdk/git/refs/heads/${{ env.GOSDK_VERSION }} | jq -r '.object.sha')
+
+        echo '#!/bin/bash
+        cd $2
+        echo "Upgrading [$3] to GOSDK [${{ env.GOSDK_VERSION }}/$1]"
+        go get github.com/0chain/gosdk@$GOSDK_HEAD || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ env.GOSDK_VERSION }}]" && exit 1; }
+        go mod tidy || { echo "::error title=Failed to upgrade $3 gosdk::failed to upgrade $3 gosdk to [${{ env.GOSDK_VERSION }}]" && exit 1; }
+        cd -
+        ' > ./upgrade-gosdk.sh;
+        chmod 777 ./upgrade-gosdk.sh
+
+        ./upgrade-gosdk.sh $GOSDK_HEAD ./zwalletcli  zwalletcli
+        ./upgrade-gosdk.sh $GOSDK_HEAD ../zboxcli    zboxcli
+
+
     - name: "Build CLI Binaries"
       shell: 'script --return --quiet --command "bash {0}"'
       run: |
@@ -478,24 +503,11 @@ runs:
         echo
         echo "Building zwalletcli [${{ env.ZWALLET_BRANCH }}]..."
         cd zwalletcli
-
-
-        if [[ -n "${{ env.GOSDK_VERSION }}" && "${{ env.GOSDK_VERSION }}" != "NONE" ]];
-        then
-          echo "Upgrading zwalletcli to GOSDK [${{ env.GOSDK_VERSION }}]"
-          GOPROXY=direct go get github.com/0chain/gosdk@${{ env.GOSDK_VERSION }} || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ env.GOSDK_VERSION }}]" && exit 1; }
-          go mod tidy || { echo "::error title=Failed to upgrade gosdk on zwallet CLI::failed to upgrade zwallet CLI gosdk to [${{ env.GOSDK_VERSION }}]" && exit 1; }
-        fi
         make install > build.log 2>&1 || { cat build.log && echo "::error title=zwallet CLI build failed::zwallet CLI build failed" && exit 1; }
         mv zwallet ..
+        
         echo "Building zboxcli [${{ env.ZBOX_BRANCH }}]..."
         cd ../zboxcli
-        if [[ -n "${{ env.GOSDK_VERSION }}" && "${{ env.GOSDK_VERSION }}" != "NONE" ]];
-        then
-          echo "Upgrading zboxcli to GOSDK [${{ env.GOSDK_VERSION }}]"
-          GOPROXY=direct go get github.com/0chain/gosdk@${{ env.GOSDK_VERSION }} || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ env.GOSDK_VERSION }}]" && exit 1; }
-          go mod tidy || { echo "::error title=Failed to upgrade gosdk on zbox CLI::failed to upgrade zbox CLI gosdk to [${{ env.GOSDK_VERSION }}]" && exit 1; }
-        fi
         make install > build.log 2>&1 || { cat build.log && echo "::error title=zbox CLI build failed::zbox CLI build failed" && exit 1; }
         mv zbox ..
         echo "CLI build SUCCESS!"
diff --git a/run-system-tests/action.yml b/run-system-tests/action.yml
--- a/run-system-tests/action.yml
+++ b/run-system-tests/action.yml
@@ -292,20 +292,22 @@ runs:
         echo "=============================================================="
         echo
         
+        GOSDK_HEAD=$(curl -s -H "Authorization: token ${{ inputs.svc_account_secret }}" https://api.github.com/repos/0chain/gosdk/git/refs/heads/${{ env.GOSDK_VERSION }} | jq -r '.object.sha')
+        
         echo '#!/bin/bash
-        cd $1
-        echo "Upgrading [$2] to GOSDK [${{ env.GOSDK_VERSION }}]"
-        GOPROXY=direct go get github.com/0chain/gosdk@${{ env.GOSDK_VERSION }} || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ env.GOSDK_VERSION }}]" && exit 1; }
-        go mod tidy || { echo "::error title=Failed to upgrade $1 gosdk::failed to upgrade $2 gosdk to [${{ env.GOSDK_VERSION }}]" && exit 1; }
+        cd $2
+        echo "Upgrading [$3] to GOSDK [${{ env.GOSDK_VERSION }}/$1]"
+        go get github.com/0chain/gosdk@$GOSDK_HEAD || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ env.GOSDK_VERSION }}]" && exit 1; }
+        go mod tidy || { echo "::error title=Failed to upgrade $3 gosdk::failed to upgrade $3 gosdk to [${{ env.GOSDK_VERSION }}]" && exit 1; }
         cd -
         ' > ./upgrade-gosdk.sh;
         chmod 777 ./upgrade-gosdk.sh
         
-        ./upgrade-gosdk.sh ./zwalletcli zwalletcli
-        ./upgrade-gosdk.sh ../zboxcli zboxcli
-        ./upgrade-gosdk.sh ../s3-migration zs3cli
-        ./upgrade-gosdk.sh ../tests/cli_tests "CLI System Tests"
-        ./upgrade-gosdk.sh ../tests/api_tests "API System Tests"
+        ./upgrade-gosdk.sh $GOSDK_HEAD ./zwalletcli       zwalletcli
+        ./upgrade-gosdk.sh $GOSDK_HEAD ../zboxcli         zboxcli
+        ./upgrade-gosdk.sh $GOSDK_HEAD ../s3-migration    zs3cli
+        ./upgrade-gosdk.sh $GOSDK_HEAD ../tests/cli_tests "CLI System Tests"
+        ./upgrade-gosdk.sh $GOSDK_HEAD ../tests/api_tests "API System Tests"
         
 
     - name: "Build CLI Binaries"
