extend script

diff --git a/deploy-0chain/action.yml b/deploy-0chain/action.yml
--- a/deploy-0chain/action.yml
+++ b/deploy-0chain/action.yml
@@ -393,7 +393,7 @@ runs:
           retry ./zwallet getblobbers --silent --configDir . --config ./zbox_config.yaml --wallet ../ignore | grep -o "[a-z0-9]\{64\}" > build.log
           num=$(cat build.log | wc -l)
 
-          echo "Stake [$count] output:"
+          echo "List Blobbers [$count] output:"
           cat build.log
           echo
 
@@ -411,6 +411,33 @@ runs:
         for id in "${blobber_ids[@]}"
         do
             retry ./zbox sp-lock --blobber_id $id --tokens 5 --configDir . --config ./zbox_config.yaml --wallet ../ignore > build.log 2>&1
+        done
+        
+        # Validator staking
+        count=0
+        while [[ $count -le 6 ]]
+        do
+          retry ./zbox ls-validators --silent --configDir . --config ./zbox_config.yaml --wallet ../ignore | grep -o "[a-z0-9]\{64\}" > build.log
+          num=$(cat build.log | wc -l)
+
+          echo "List Validators [$count] output:"
+          cat build.log
+          echo
+
+          [[ $num -eq 7 ]] && break
+          sleep 10
+          ((count++))
+        done
+        if [[ $num -lt 7 ]]
+        then
+          echo "::error title=Number of Validators registered is less than 7:: Only ${num}/7 validators are registered. Exiting run..."
+          cat build.log
+          exit 1
+        fi
+        readarray -t validator_ids < build.log
+        for id in "${validator_ids[@]}"
+        do
+            retry ./zbox sp-lock --validator_id $id --tokens 5 --configDir . --config ./zbox_config.yaml --wallet ../ignore > build.log 2>&1
         done
         ' > ./stake_blobbers.sh;
         chmod 777 ./stake_blobbers.sh;
