enhance retry to helmchart deploy if it fails to load in action.yml

diff --git a/deploy-0chain/action.yml b/deploy-0chain/action.yml
--- a/deploy-0chain/action.yml
+++ b/deploy-0chain/action.yml
@@ -243,41 +243,140 @@ runs:
         ./add-configmap.sh delegate-wallet-json
         ./add-configmap.sh nodes
 
-        sleep 2s && helm repo update
+        #COUNT is the total count set for installing all 7 helmcharts i.e. 0chain, 0dns, blobber, 0box, authorizer, graphnode, ipfs. Will be giving 3 try to install the helmchart.
+        COUNT=21
+        
+        #RET is used to get the success/fail status of latest commanf executed
+        RET=1
+        
+        ##############----------------- Installing 0chain helm-chart --------------------###################
+        while [[ $RET -ne 0 && $COUNT -gt 18 ]]; do
+           helm upgrade --install 0chain --wait --timeout 10m  0chain-helm/zchainDel --set sharder.hostName=${{ env.NAMESPACE }} --set sharder.host=devnet-0chain.net --set sharder.image.tag=${{ env.SHARDER_TAG }} \
+             --set sharder.config.zchain01.delegate_wallet="b888ae3400b67a47362aad7d6263fcfeb6585fe696e8d182d3bb4f4a9d737bae" \
+             --set sharder.config.zchain02.delegate_wallet="b3e3f587dd65aaf4118adf87878a138dbb3163a3b169a0d1872aa9a7a0fa5c50" \
+             --set miner.config.zchain01.delegate_wallet="9636ab821fd93a37740ab4c6a27d9e2cf3a4072b4bc8fd1c6048f9c3ef9cf2a8" \
+             --set miner.config.zchain02.delegate_wallet="b8b25d509afbe8f68f1342a2fa719acf312915a6f5a5bb0918cad6598e01325f" \
+             --set miner.config.zchain03.delegate_wallet="bbe8b6abdb54b0642324a103c49f8b04e2623db74cd7f1427cd2d5f0308e674d" \
+             --set commonConf.zchainUp.server_chain.transaction.timeout=600 \
+             --set miner.hostName=${{ env.NAMESPACE }} \
+             --set miner.host=devnet-0chain.net \
+             --set miner.image.tag=${{ env.MINER_TAG }} \
+             --set commonConf.zchainUp.server_chain.transaction.min_fee=${{ env.MINER_FEE }} \
+             --set commonConf.zchainUp.server_chain.transaction.max_fee=0.01 \
+             --set commonConf.zchainUp.server_chain.smart_contract.multisig=true \
+             --set commonConf.zchainUp.server_chain.smart_contract.vesting=true \
+             --set commonConf.zchainUp.server_chain.dbs.events.aggregate_period=11 \
+             --set commonConf.zchainUp.server_chain.smart_contract.setting_update_period=2 \
+             --set commonConf.zchainUp.server_chain.dbs.settings.debug=true \
+             --set commonConf.sc.smart_contracts.minersc.num_sharders_rewarded=5 \
+             --set commonConf.sc.smart_contracts.minersc.num_sharder_delegates_rewarded=1 \
+             --set commonConf.sc.smart_contracts.storagesc.time_unit="1m" \
+             --set commonConf.sc.smart_contracts.storagesc.cost.cancel_allocation=5000 \
+             -n ${{ env.NAMESPACE }} --kubeconfig ./kube/${{ env.NAMESPACE }}-config || exit 1;
+           RET=$?
+           ((COUNT--))
+           echo "Retrying helm install"
+           sleep 2
+        done
 
-        helm upgrade --install 0chain --wait --timeout 10m  0chain-helm/zchainDel --set sharder.hostName=${{ env.NAMESPACE }} --set sharder.host=devnet-0chain.net --set sharder.image.tag=${{ env.SHARDER_TAG }} \
-          --set sharder.config.zchain01.delegate_wallet="b888ae3400b67a47362aad7d6263fcfeb6585fe696e8d182d3bb4f4a9d737bae" \
-          --set sharder.config.zchain02.delegate_wallet="b3e3f587dd65aaf4118adf87878a138dbb3163a3b169a0d1872aa9a7a0fa5c50" \
-          --set miner.config.zchain01.delegate_wallet="9636ab821fd93a37740ab4c6a27d9e2cf3a4072b4bc8fd1c6048f9c3ef9cf2a8" \
-          --set miner.config.zchain02.delegate_wallet="b8b25d509afbe8f68f1342a2fa719acf312915a6f5a5bb0918cad6598e01325f" \
-          --set miner.config.zchain03.delegate_wallet="bbe8b6abdb54b0642324a103c49f8b04e2623db74cd7f1427cd2d5f0308e674d" \
-          --set commonConf.zchainUp.server_chain.transaction.timeout=600 \
-          --set miner.hostName=${{ env.NAMESPACE }} \
-          --set miner.host=devnet-0chain.net \
-          --set miner.image.tag=${{ env.MINER_TAG }} \
-          --set commonConf.zchainUp.server_chain.transaction.min_fee=${{ env.MINER_FEE }} \
-          --set commonConf.zchainUp.server_chain.transaction.max_fee=0.01 \
-          --set commonConf.zchainUp.server_chain.smart_contract.multisig=true \
-          --set commonConf.zchainUp.server_chain.smart_contract.vesting=true \
-          --set commonConf.zchainUp.server_chain.dbs.events.aggregate_period=11 \
-          --set commonConf.zchainUp.server_chain.smart_contract.setting_update_period=2 \
-          --set commonConf.zchainUp.server_chain.dbs.settings.debug=true \
-          --set commonConf.sc.smart_contracts.minersc.num_sharders_rewarded=5 \
-          --set commonConf.sc.smart_contracts.minersc.num_sharder_delegates_rewarded=1 \
-          --set commonConf.sc.smart_contracts.storagesc.time_unit="1m" \
-          --set commonConf.sc.smart_contracts.storagesc.cost.cancel_allocation=5000 \
-          -n ${{ env.NAMESPACE }} --kubeconfig ./kube/${{ env.NAMESPACE }}-config || exit 1;
+        ##############----------------- Installing 0dns helm-chart --------------------###################
+        while [[ $RET -ne 0 && $COUNT -gt 18 ]]; do
+           helm upgrade --install 0dns --wait --timeout 60s \
+             --set zdns.image.tag=${{ env.ZDNS_TAG }} \
+             --set zdns.hostName=${{ env.NAMESPACE }} \
+             --set zdns.host=devnet-0chain.net \
+             -n ${{ env.NAMESPACE }}  0chain-helm/zdns --kubeconfig ./kube/${{ env.NAMESPACE }}-config
+           RET=$?
+           ((COUNT--))
+           echo "Retrying helm install"
+           sleep 2
+        done
+        
+        ##############----------------- Installing blobber helm-chart --------------------###################
+        while [[ $RET -ne 0 && $COUNT -gt 18 ]]; do
+           helm upgrade --install blobber --wait --timeout 120s \
+             --set blobber.blobberCount=6 \
+             --set validator.validatorCount=6 \
+             --set blobber.config.read_price=0.01 \
+             --set blobber.config.price_in_usd="false" \
+             --set blobber.config.block_worker=https://${{ env.NAMESPACE }}.devnet-0chain.net/dns \
+             --set validator.config.block_worker=https://${{ env.NAMESPACE }}.devnet-0chain.net/dns \
+             --set blobber.config.delegate_wallet=591d6d0d5642bdbc924756ca2647b4b59adce0acd02a487ecc4d1bd4669293a8 \
+             --set validator.config.delegate_wallet=591d6d0d5642bdbc924756ca2647b4b59adce0acd02a487ecc4d1bd4669293a8 \
+             --set blobber.hostName=${{ env.NAMESPACE }} \
+             --set blobber.host=devnet-0chain.net \
+             --set blobber.image.tag=${{ env.BLOBBER_TAG }} \
+             --set validator.image.tag=${{ env.VALIDATOR_TAG }} \
+             --set validator.hostName=${{ env.NAMESPACE }} \
+             --set validator.host=devnet-0chain.net -n ${{ env.NAMESPACE }} \
+             0chain-helm/blobber --kubeconfig ./kube/${{ env.NAMESPACE }}-config
+           RET=$?
+           ((COUNT--))
+           echo "Retrying helm install"
+           sleep 2
+        done
+        
+        ##############----------------- Installing 0box helm-chart --------------------###################
+        while [[ $RET -ne 0 && $COUNT -gt 18 ]]; do
+           helm upgrade --install 0box --wait \
+             --set zbox.hostName=${{ env.NAMESPACE }} \
+             --set zbox.host=devnet-0chain.net \
+             --set zbox.config.host=https://${{ env.NAMESPACE }}.devnet-0chain.net/ \
+             --set zbox.config.block_worker=https://${{ env.NAMESPACE }}.devnet-0chain.net/dns \
+             --set zbox.config.graph_node.network=${{ env.NAMESPACE }} \
+             --set zbox.config.graph_node.domain=devnet-0chain.net \
+             --set zbox.image.tag=${{ env.ZBOX_TAG }} -n ${{ env.NAMESPACE }} \
+             0chain-helm/zbox --kubeconfig ./kube/${{ env.NAMESPACE }}-config
+           RET=$?
+           ((COUNT--))
+           echo "Retrying helm install"
+           sleep 2
+        done
 
-        sleep 2s && helm repo update
-        helm upgrade --install 0dns --wait --timeout 60s --set zdns.image.tag=${{ env.ZDNS_TAG }} --set zdns.hostName=${{ env.NAMESPACE }} --set zdns.host=devnet-0chain.net -n ${{ env.NAMESPACE }}  0chain-helm/zdns --kubeconfig ./kube/${{ env.NAMESPACE }}-config
-        sleep 2s && helm repo update
-        helm upgrade --install blobber --wait --timeout 120s --set blobber.blobberCount=6 --set validator.validatorCount=6 --set blobber.config.read_price=0.01 --set blobber.config.price_in_usd="false" --set blobber.config.block_worker=https://${{ env.NAMESPACE }}.devnet-0chain.net/dns --set validator.config.block_worker=https://${{ env.NAMESPACE }}.devnet-0chain.net/dns --set blobber.config.delegate_wallet=591d6d0d5642bdbc924756ca2647b4b59adce0acd02a487ecc4d1bd4669293a8 --set validator.config.delegate_wallet=591d6d0d5642bdbc924756ca2647b4b59adce0acd02a487ecc4d1bd4669293a8 --set blobber.hostName=${{ env.NAMESPACE }} --set blobber.host=devnet-0chain.net --set blobber.image.tag=${{ env.BLOBBER_TAG }} --set validator.image.tag=${{ env.VALIDATOR_TAG }} --set validator.hostName=${{ env.NAMESPACE }} --set validator.host=devnet-0chain.net -n ${{ env.NAMESPACE }}  0chain-helm/blobber --kubeconfig ./kube/${{ env.NAMESPACE }}-config
-        sleep 2s && helm repo update
-        helm upgrade --install 0box --wait --set zbox.hostName=${{ env.NAMESPACE }} --set zbox.host=devnet-0chain.net --set zbox.config.host=https://${{ env.NAMESPACE }}.devnet-0chain.net/ --set zbox.config.block_worker=https://${{ env.NAMESPACE }}.devnet-0chain.net/dns --set zbox.config.graph_node.network=${{ env.NAMESPACE }} --set zbox.config.graph_node.domain=devnet-0chain.net --set zbox.image.tag=${{ env.ZBOX_TAG }} -n ${{ env.NAMESPACE }}  0chain-helm/zbox --kubeconfig ./kube/${{ env.NAMESPACE }}-config
-        sleep 2s && helm repo update
-        helm upgrade --install ipfs --wait -n ${{ env.NAMESPACE }} --set ipfs.hostName=${{ env.NAMESPACE }} --set ipfs.host=devnet-0chain.net --set ipfs.image.tag=latest 0chain-helm/ipfs --kubeconfig ./kube/${{ env.NAMESPACE }}-config
-        helm upgrade --install graph-node --wait -n ${{ env.NAMESPACE }} --set graphNode.hostName=${{ env.NAMESPACE }} --set graphNode.host=devnet-0chain.net --set graphNode.image.tag=latest --set graphNode.config.ethereum_node_url=${{ env.GRAPHNODE_ETHEREUM_NODE_URL }} --set graphNode.config.network=${{ env.GRAPHNODE_NETWORK }} --set graphNode.config.private_fork=true 0chain-helm/graphNode --kubeconfig ./kube/${{ env.NAMESPACE }}-config
-        helm upgrade --install authorizer -n ${{ env.NAMESPACE }} --set authorizer.authorizerCount=3 --set authorizer.hostName=${{ env.NAMESPACE }} --set authorizer.host=devnet-0chain.net --set authorizer.image.tag=${{ env.AUTHORIZER_TAG }} --set authorizer.config.config_yaml.block_worker=https://${{ env.NAMESPACE }}.devnet-0chain.net/dns --set authorizer.config.config_yaml.ethereum_node_url=${{ env.ETHEREUM_NODE_URL }} 0chain-helm/authorizer --kubeconfig ./kube/${{ env.NAMESPACE }}-config
+        ##############----------------- Installing ipfs helm-chart --------------------###################
+        while [[ $RET -ne 0 && $COUNT -gt 18 ]]; do
+           helm upgrade --install ipfs --wait \
+             --set ipfs.hostName=${{ env.NAMESPACE }} \
+             --set ipfs.host=devnet-0chain.net \
+             --set ipfs.image.tag=latest -n ${{ env.NAMESPACE }} \
+             0chain-helm/ipfs --kubeconfig ./kube/${{ env.NAMESPACE }}-config
+           RET=$?
+           ((COUNT--))
+           echo "Retrying helm install"
+           sleep 2
+        done
+
+        ##############----------------- Installing graph-node helm-chart --------------------###################
+        while [[ $RET -ne 0 && $COUNT -gt 18 ]]; do
+           helm upgrade --install graph-node --wait \
+             --set graphNode.hostName=${{ env.NAMESPACE }} \
+             --set graphNode.host=devnet-0chain.net \
+             --set graphNode.image.tag=latest \
+             --set graphNode.config.ethereum_node_url=${{ env.GRAPHNODE_ETHEREUM_NODE_URL }} \
+             --set graphNode.config.network=${{ env.GRAPHNODE_NETWORK }} \
+             --set graphNode.config.private_fork=true \
+             -n ${{ env.NAMESPACE }} 0chain-helm/graphNode --kubeconfig ./kube/${{ env.NAMESPACE }}-config
+           RET=$?
+           ((COUNT--))
+           echo "Retrying helm install"
+           sleep 2
+        done
+
+        ##############----------------- Installing authorizer helm-chart --------------------###################
+        while [[ $RET -ne 0 && $COUNT -gt 18 ]]; do
+           helm upgrade --install authorizer \
+             --set authorizer.authorizerCount=3 \
+             --set authorizer.hostName=${{ env.NAMESPACE }} \
+             --set authorizer.host=devnet-0chain.net \
+             --set authorizer.image.tag=${{ env.AUTHORIZER_TAG }} \
+             --set authorizer.config.config_yaml.block_worker=https://${{ env.NAMESPACE }}.devnet-0chain.net/dns \
+             --set authorizer.config.config_yaml.ethereum_node_url=${{ env.ETHEREUM_NODE_URL }} \
+             -n ${{ env.NAMESPACE }} 0chain-helm/authorizer --kubeconfig ./kube/${{ env.NAMESPACE }}-config
+           RET=$?
+           ((COUNT--))
+           echo "Retrying helm install"
+           sleep 2
+        done
         ' > ./deploy.sh;
         chmod 777 ./deploy.sh;
         ./deploy.sh
