migrate blobber-stake to deploy job

diff --git a/deploy-0chain/action.yml b/deploy-0chain/action.yml
--- a/deploy-0chain/action.yml
+++ b/deploy-0chain/action.yml
@@ -175,6 +175,101 @@ runs:
         chmod 777 ./deploy.sh;
         ./deploy.sh
 
+    - name: "Build CLI Binaries"
+#      if: steps.cli-cache.outputs.cache-hit != 'true'
+      shell: 'script --return --quiet --command "bash {0}"'
+      run: |
+        echo
+        echo "======================================================"
+        echo "BUILDING 0WALLET AND 0BOX CLI BINARIES:"
+        echo "======================================================"
+        echo
+        echo "Building zwalletcli [${{ env.ZWALLET_BRANCH }}]..."
+        cd zwalletcli
+        if [[ -n "${{ inputs.custom_go_sdk_version }}" && "${{ inputs.custom_go_sdk_version }}" != "NONE" ]];
+        then
+          echo "Upgrading zwalletcli to GOSDK [${{ inputs.custom_go_sdk_version }}]"
+          go get github.com/0chain/gosdk@${{ inputs.custom_go_sdk_version }} || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ inputs.custom_go_sdk_version }}]" && exit 1; }
+          go mod tidy || { echo "::error title=Failed to upgrade gosdk on zwallet CLI::failed to upgrade zwallet CLI gosdk to [${{ inputs.custom_go_sdk_version }}]" && exit 1; }
+        fi
+        make install > build.log 2>&1 || { cat build.log && echo "::error title=zwallet CLI build failed::zwallet CLI build failed" && exit 1; }
+        mv zwallet ../tests/cli_tests
+        echo "Building zboxcli [${{ env.ZBOX_BRANCH }}]..."
+        cd ../zboxcli
+        if [[ -n "${{ inputs.custom_go_sdk_version }}" && "${{ inputs.custom_go_sdk_version }}" != "NONE" ]];
+        then
+          echo "Upgrading zboxcli to GOSDK [${{ inputs.custom_go_sdk_version }}]"
+          go get github.com/0chain/gosdk@${{ inputs.custom_go_sdk_version }} || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ inputs.custom_go_sdk_version }}]" && exit 1; }
+          go mod tidy || { echo "::error title=Failed to upgrade gosdk on zbox CLI::failed to upgrade zbox CLI gosdk to [${{ inputs.custom_go_sdk_version }}]" && exit 1; }
+        fi
+        make install > build.log 2>&1 || { cat build.log && echo "::error title=zbox CLI build failed::zbox CLI build failed" && exit 1; }
+        mv zbox ../tests/cli_tests
+        echo "CLI build SUCCESS!"
+
+      - name: "Stake blobbers using above built binaries"
+      shell: 'script --return --quiet --command "bash {0}"'
+      run: |
+        echo '#!/bin/bash
+        echo
+        echo "==========================================================="
+        echo "STAKING BLOBBERS USING ZWALLETCLI & ZBOXCLI BINARIES"
+        echo "==========================================================="
+        echo
+        cd tests/cli_tests
+        exec 6>&1 # Save stdout to file descriptor 6
+        function retry {
+            local n=1
+            local max=5
+            local delay=5
+            while true; do
+            "$@" && break || {
+                if [[ $n -lt $max ]]; then
+                    ((n++))
+                    echo "Command failed. Attempt $n/$max:"
+                    sleep $delay;
+                else
+                    exec 1>&6 6>&- # Revert output to stdout instead of build.log and close file descriptor 6
+                    echo "failed to run $@"
+                    cat build.log && echo "::error title=Failed to stake the blobbers";
+                    echo "exiting blobber stake process..."
+                    exit 1
+                fi
+            }
+            done
+        }
+        retry ./zwallet register --configDir ./config --config ./zbox_config.yaml --wallet ../ignore > build.log 2>&1
+        for i in {1..6}
+        do
+            retry ./zwallet faucet --methodName "pour" --input "{}" --tokens 2 --configDir ./config --config ./zbox_config.yaml --wallet ../ignore > build.log 2>&1
+        done
+
+        retry ./zwallet getblobbers --silent --configDir ./config --config ./zbox_config.yaml --wallet ../ignore | grep -o "[a-z0-9]\{64\}" > build.log
+        readarray -t blobber_ids < build.log
+        for id in "${blobber_ids[@]}"
+        do
+            retry ./zbox sp-lock --blobber_id $id --tokens 1 --configDir ./config --config ./zbox_config.yaml --wallet ../ignore > build.log 2>&1
+        done
+        ' > ./stake_blobbers.sh;
+        chmod 777 ./stake_blobbers.sh;
+
+        ITER=0
+        MAX_RETRIES=3
+        until [[ $ITER -eq $MAX_RETRIES ]]
+        do
+            ./stake_blobbers.sh && break
+            ITER=$((ITER+1))
+            echo "Staking blobbers failed on try $ITER. Retrying in 5 seconds..."
+            sleep 5
+        done
+
+        if [[ $ITER -eq $MAX_RETRIES ]]
+          then
+            echo "Staking blobbers failed after $MAX_RETRIES tries. Exiting run..."
+            exit 1
+          else
+            echo "Blobbers staked succefully on try $((ITER+1)). Moving on to tests..."
+        fi
+
     - name: "Create post run teardown script"
       shell: 'script --return --quiet --command "bash {0}"'
       run: |
