debug

diff --git a/deploy-0chain-enterprise-blobber/action.yml b/deploy-0chain-enterprise-blobber/action.yml
--- a/deploy-0chain-enterprise-blobber/action.yml
+++ b/deploy-0chain-enterprise-blobber/action.yml
@@ -1,4 +1,4 @@
-name: "Deploy 0Chain Network"
+name: "Deploy 0chain enterprise blobbers network."
 description: "Deploy 0Chain Network to k8s cluster using helm"
 inputs:
   kube_config:
@@ -261,7 +261,6 @@ runs:
         ./add-configmap.sh nodes
 
 
-
         ##############----------------- Installing kafka helm-chart --------------------###################
         COUNT=3       #COUNT will be giving 3 try to install the helmchart.
         RET=1         #You can set RET=0 to skip the kafka helm-chart deployment
@@ -359,8 +358,8 @@ runs:
         RET=1         #You can set RET=0 to skip the blobber helm-chart deployment
         while [[ $RET -ne 0 && $COUNT -gt 0 ]]; do
            helm upgrade --install blobber --wait --timeout 120s \
-             --set blobber.blobberCount=3 \
-             --set validator.validatorCount=3 \
+             --set blobber.blobberCount=2 \
+             --set validator.validatorCount=2 \
              --set blobber.config.read_price=0.01 \
              --set blobber.config.price_in_usd="false" \
              --set blobber.config.writemarker_redeem.max_chain_length=1 \
@@ -460,6 +459,37 @@ runs:
         fetch-depth: 1
         path: ./zboxcli
 
+    - name: "Upgrade GoSDK"
+      shell: 'script --return --quiet --command "bash {0}"'
+      if: ${{ env.GOSDK_VERSION != '' && env.GOSDK_VERSION != 'NONE' }}
+      run: |
+        echo
+        echo "=============================================================="
+        echo "UPGRADING GOSDK IN ZBOXCLI, ZWALLETCLI"
+        echo "=============================================================="
+        echo
+
+        GOSDK_HEAD=$(curl -s -H "Authorization: token ${{ inputs.svc_account_secret }}" https://api.github.com/repos/0chain/gosdk/git/refs/heads/${{ env.GOSDK_VERSION }} | jq -r '.object.sha')
+        if [[ "$GOSDK_HEAD" == "null" ]]; then
+            echo "[${{ env.GOSDK_VERSION }}] does not seem to be a valid branch (possibly a commit hash?). Will pass directly to go to resolve"
+            GOSDK_HEAD="${{ env.GOSDK_VERSION }}"
+        fi
+
+        echo '#!/bin/bash
+        echo "Upgrading [$2] to GOSDK [${{ env.GOSDK_VERSION }}($1)]"
+        go clean -modcache -cache
+        go get github.com/0chain/gosdk@$1 || { echo "::error title=Failed to retrieve gosdk::failed to retrieve gosdk [${{ env.GOSDK_VERSION }}]" && exit 1; }
+        go mod tidy || { echo "::error title=Failed to upgrade $2 gosdk::failed to upgrade $2 gosdk to [${{ env.GOSDK_VERSION }}]" && exit 1; }
+        ' > ./upgrade-gosdk.sh;
+        chmod 555 ./upgrade-gosdk.sh
+
+        cd ./zwalletcli
+        ../upgrade-gosdk.sh $GOSDK_HEAD zwalletcli
+        cd ../zboxcli
+        ../upgrade-gosdk.sh $GOSDK_HEAD zboxcli
+
+        sudo rm -rf upgrade-gosdk.sh
+
 
     - name: "Build CLI Binaries"
       shell: 'script --return --quiet --command "bash {0}"'
@@ -545,6 +575,7 @@ runs:
         # ./zwallet add-hardfork -n athena -r 0 --wallet owner_wallet.json --config ./zbox_config.yaml --configDir .
         # ./zwallet add-hardfork -n demeter -r 0 --wallet owner_wallet.json --config ./zbox_config.yaml --configDir .
         # ./zwallet add-hardfork -n electra -r 0 --wallet owner_wallet.json --config ./zbox_config.yaml --configDir .
+
 
     - name: "Wait for 0Chain network deployment to complete"
       shell: 'script --return --quiet --command "bash {0}"'
