add gosdk branch

diff --git a/.github/workflows/manual_system_tests.yml b/.github/workflows/manual_system_tests.yml
--- a/.github/workflows/manual_system_tests.yml
+++ b/.github/workflows/manual_system_tests.yml
@@ -94,9 +94,9 @@ on:
          default: 'staging'
          required: true
          type: string
-       custom_go_sdk_version:
-         description: 'gosdk version to inject into the CLIs'
-         default: 'NONE'
+       gosdk_branch:
+         description: 'gosdk branch to inject into the CLIs'
+         default: 'NOT OVERRIDDEN'
          required: false
          type: string
        skip_tests:
@@ -115,6 +115,7 @@ jobs:
       run: |
         echo "NETWORK_URL=$(echo dev-${RUNNER_NAME:(-1)}.devnet-0chain.net)" >> $GITHUB_ENV
         echo "RUNNER_NUMBER=${RUNNER_NAME:(-1)}" >> $GITHUB_ENV
+        echo "GOSDK_SHA=$(curl --silent --fail -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/repos/0chain/gosdk/git/refs/heads/${{ inputs.gosdk_branch }} | jq --raw-output .object.sha || echo 'NONE')" >> $GITHUB_ENV
 
         echo '#!/bin/bash
 
@@ -175,7 +176,53 @@ jobs:
         ./get_tag.sh 0proxy ${{ inputs.zproxy_branch }} 0proxy
         ./get_tag.sh 0search ${{ inputs.zsearch_branch }} 0search
 
+    - name: "Set PR Status Pending"
+      uses: 0chain/actions/notify-pull-request@feature/notify-PR-convenience
+      continue-on-error: true
+      with:
+        state: "pending"
+        message: "manually running against system_test branch [${{ inputs.system_tests_branch }}]"
+        system_tests_branch: ${{ inputs.system_tests_branch }}
+        zbox_cli_branch: ${{ inputs.zbox_cli_branch }}
+        zwallet_cli_branch: ${{ inputs.zwallet_cli_branch }}
+        zerochain_branch: ${{ inputs.miner_branch }}
+        blobber_branch: ${{ inputs.blobber_branch }}
+        gosdk_branch: ${{ inputs.gosdk_branch }}
+        github_token: ${{ secrets.SVC_ACCOUNT_SECRET }}
 
+    - name: "Deploy 0Chain"
+      if: ${{ inputs.skip_tests == 'FALSE' }}
+      uses: 0chain/actions/deploy-0chain@master
+      with:
+        kube_config: ${{ secrets[format('DEV{0}KC', env.RUNNER_NUMBER)] }}
+        teardown_condition: "TESTS_PASSED"
+        miner_image:  ${{ env.MINER_TAG }}
+        sharder_image: ${{ env.SHARDER_TAG }}
+        blobber_image: ${{ env.BLOBBER_TAG }}
+        validator_image: ${{ env.VALIDATOR_TAG }}
+        zbox_image: ${{ env.ZBOX_TAG }}
+        zblock_image: ${{ env.ZBLOCK_TAG }}
+        zdns_image: ${{ env.ZDNS_TAG }}
+        explorer_image: ${{ env.EXPLORER_TAG }}
+        zproxy_image: ${{ env.ZPROXY_TAG }}
+        zsearch_image: ${{ env.ZSEARCH_TAG }}
+        blobber_stake_image: latest
+
+    - name: "Run System tests"
+      if: ${{ inputs.skip_tests == 'FALSE' }}
+      uses: 0chain/actions/run-system-tests@feature/notify-PR-convenience
+      with:
+        system_tests_branch: ${{ inputs.system_tests_branch }}
+        network: ${{ env.NETWORK_URL }}
+        zbox_cli_branch: ${{ inputs.zbox_cli_branch }}
+        zwallet_cli_branch: ${{ inputs.zwallet_cli_branch }}
+        custom_go_sdk_version: ${{ env.GOSDK_SHA }}
+        smart_contract_owner_wallet_json: ${{ secrets.SMART_CONTRACT_OWNER_WALLET_JSON }}
+        svc_account_secret: ${{ github.token }}
+        deploy_report_page: false
+        archive_results: true
+        run_flaky_tests: false
+        retry_failures: true
 
     - name: "Set PR Status"
       if: ${{ success() || failure() }}
@@ -183,10 +230,11 @@ jobs:
       continue-on-error: true
       with:
         state: ${{ job.status }}
-        message: "manually ran against [${{ inputs.system_tests_branch }}]"
+        message: "manually ran against system_test branch [${{ inputs.system_tests_branch }}]"
         system_tests_branch: ${{ inputs.system_tests_branch }}
         zbox_cli_branch: ${{ inputs.zbox_cli_branch }}
         zwallet_cli_branch: ${{ inputs.zwallet_cli_branch }}
         zerochain_branch: ${{ inputs.miner_branch }}
         blobber_branch: ${{ inputs.blobber_branch }}
+        gosdk_branch: ${{ inputs.gosdk_branch }}
         github_token: ${{ secrets.SVC_ACCOUNT_SECRET }}
