fix(manual_system_tests): fixed sha for pr

diff --git a/.github/workflows/manual_system_tests.yml b/.github/workflows/manual_system_tests.yml
--- a/.github/workflows/manual_system_tests.yml
+++ b/.github/workflows/manual_system_tests.yml
@@ -157,13 +157,15 @@ jobs:
           exit 1
         fi
 
+        #MERGE_SHORT_SHA=$(curl --silent -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/repos/0chain/$1/pulls/$PR_ID | jq --raw-output .merge_commit_sha | head -c 8)
+
         exit_code=0
-        MERGE_SHORT_SHA=$(curl --silent -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/repos/0chain/$1/pulls/$PR_ID | jq --raw-output .merge_commit_sha | head -c 8)
-        echo "Searching for image [pr-$PR_ID-$MERGE_SHORT_SHA]..."
-        docker pull 0chaindev/$3:pr-$PR_ID-$MERGE_SHORT_SHA > /dev/null 2>&1 || exit_code=$?
+       
+        echo "Searching for image [pr-$PR_ID-$SHORT_SHA]..."
+        docker pull 0chaindev/$3:pr-$PR_ID-$SHORT_SHA > /dev/null 2>&1 || exit_code=$?
         if [[ $exit_code == 0 ]];then
-            echo "Docker image [pr-$PR_ID-$MERGE_SHORT_SHA] found"
-            echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=pr-$PR_ID-$MERGE_SHORT_SHA" >> $GITHUB_ENV
+            echo "Docker image [pr-$PR_ID-$SHORT_SHA] found"
+            echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=pr-$PR_ID-$SHORT_SHA" >> $GITHUB_ENV
 
             unset SHORT_SHA
             unset PR_ID
@@ -173,12 +175,12 @@ jobs:
         fi
 
         exit_code=0
-        MERGE_SHORT_SHA=$(curl --silent -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/repos/0chain/$1/pulls/$PR_ID | jq --raw-output .merge_commit_sha | head -c 8)
-        echo "Searching for image [merge-$MERGE_SHORT_SHA]..."
-        docker pull 0chaindev/$3:merge-$MERGE_SHORT_SHA > /dev/null 2>&1 || exit_code=$?
+      
+        echo "Searching for image [merge-$SHORT_SHA]..."
+        docker pull 0chaindev/$3:merge-$SHORT_SHA > /dev/null 2>&1 || exit_code=$?
         if [[ $exit_code == 0 ]];then
-            echo "Docker image [merge-$MERGE_SHORT_SHA] found"
-            echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
+            echo "Docker image [merge-$SHORT_SHA] found"
+            echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=merge-$SHORT_SHA" >> $GITHUB_ENV
 
             unset SHORT_SHA
             unset PR_ID
@@ -193,7 +195,7 @@ jobs:
         unset TAG
         unset MERGE_SHORT_SHA
 
-        echo "::error title=$3 docker image not found::$3 docker image could not be found with tags [${TAG}-${SHORT_SHA}], [pr-$PR_ID-$MERGE_SHORT_SHA] or [merge-$MERGE_SHORT_SHA]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again"
+        echo "::error title=$3 docker image not found::$3 docker image could not be found with tags [${TAG}-${SHORT_SHA}], [pr-$PR_ID-$SHORT_SHA] or [merge-$SHORT_SHA]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again"
         exit 1; 
 
         ' > ./get_tag.sh;
