improve logging

diff --git a/.github/workflows/manual_system_tests.yml b/.github/workflows/manual_system_tests.yml
--- a/.github/workflows/manual_system_tests.yml
+++ b/.github/workflows/manual_system_tests.yml
@@ -141,7 +141,7 @@ jobs:
             echo "Docker image NOT found for [${TAG}-${SHORT_SHA}]"
             MERGE_SHORT_SHA=$(curl --silent -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/repos/0chain/$1/pulls/$PR_ID | jq --raw-output .merge_commit_sha | head -c 8)
             echo "Searching for image [merge-$MERGE_SHORT_SHA]..."
-            docker pull 0chaindev/$3:merge-$MERGE_SHORT_SHA > /dev/null 2>&1 || { echo "::error title=$3 docker image not found::$3 docker image could not be found with tag [merge-$MERGE_SHORT_SHA]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again" && exit 1; }
+            docker pull 0chaindev/$3:merge-$MERGE_SHORT_SHA > /dev/null 2>&1 || { echo "::error title=$3 docker image not found::$3 docker image could not be found with tags [${TAG}-${SHORT_SHA}] or [merge-$MERGE_SHORT_SHA]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again" && exit 1; }
             echo "Docker image [merge-$MERGE_SHORT_SHA] found"
             echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
         fi
