fix(manual_system_tests): fixed tag bug for merge-sha

diff --git a/.github/workflows/manual_system_tests.yml b/.github/workflows/manual_system_tests.yml
--- a/.github/workflows/manual_system_tests.yml
+++ b/.github/workflows/manual_system_tests.yml
@@ -113,6 +113,11 @@ jobs:
 
     - name: "Setup Test Run"
       run: |
+        unset SHORT_SHA
+        unset PR_ID
+        unset TAG
+        unset MERGE_SHORT_SHA
+
         echo "NETWORK_URL=$(echo dev-${RUNNER_NAME:(-1)}.devnet-0chain.net)" >> $GITHUB_ENV
         echo "RUNNER_NUMBER=${RUNNER_NAME:(-1)}" >> $GITHUB_ENV
 
@@ -143,11 +148,6 @@ jobs:
         if [[ $exit_code == 0 ]];then
           echo "Docker image [${TAG}-${SHORT_SHA}] found"
           echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=${TAG}-${SHORT_SHA}" >> $GITHUB_ENV
-
-          unset SHORT_SHA
-          unset PR_ID
-          unset TAG
-          unset MERGE_SHORT_SHA
           exit 0
         fi
 
@@ -166,36 +166,20 @@ jobs:
         if [[ $exit_code == 0 ]];then
             echo "Docker image [pr-$PR_ID-$SHORT_SHA] found"
             echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=pr-$PR_ID-$SHORT_SHA" >> $GITHUB_ENV
-
-            unset SHORT_SHA
-            unset PR_ID
-            unset TAG
-            unset MERGE_SHORT_SHA
             exit 0
         fi
 
         exit_code=0
       
-        echo "Searching for image [merge-$SHORT_SHA]..."
-        docker pull 0chaindev/$3:merge-$SHORT_SHA > /dev/null 2>&1 || exit_code=$?
+        echo "Searching for image [merge-$MERGE_SHORT_SHA]..."
+        docker pull 0chaindev/$3:merge-$MERGE_SHORT_SHA > /dev/null 2>&1 || exit_code=$?
         if [[ $exit_code == 0 ]];then
-            echo "Docker image [merge-$SHORT_SHA] found"
-            echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=merge-$SHORT_SHA" >> $GITHUB_ENV
-
-            unset SHORT_SHA
-            unset PR_ID
-            unset TAG
-            unset MERGE_SHORT_SHA
+            echo "Docker image [merge-$MERGE_SHORT_SHA] found"
+            echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
             exit 0
         fi
 
-        unset exit_code
-        unset SHORT_SHA
-        unset PR_ID
-        unset TAG
-        unset MERGE_SHORT_SHA
-
-        echo "::error title=$3 docker image not found::$3 docker image could not be found with tags [${TAG}-${SHORT_SHA}], [pr-$PR_ID-$SHORT_SHA] or [merge-$SHORT_SHA]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again"
+        echo "::error title=$3 docker image not found::$3 docker image could not be found with tags [${TAG}-${SHORT_SHA}], [pr-$PR_ID-$SHORT_SHA] or [merge-$MERGE_SHORT_SHA]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again"
         exit 1; 
 
         ' > ./get_tag.sh;
