Add authorizor branch to CI (#13)
* Add authorizor branch to CI

* Update manual tests workflow to point to current branch

* fix PR lookup bug

* improve logging and fix null bug

* improve logging and fix null bug

* improve logging and fix null bug

* improve logging and fix null bug

* fix typo

* fix typo

* revert wallet creation location for now

* revert to master

diff --git a/.github/workflows/manual_system_tests.yml b/.github/workflows/manual_system_tests.yml
--- a/.github/workflows/manual_system_tests.yml
+++ b/.github/workflows/manual_system_tests.yml
@@ -64,6 +64,11 @@ on:
         default: 'staging'
         required: true
         type: string
+       authorizer_branch:
+         description: 'authorizer branch to deploy'
+         default: 'staging'
+         required: true
+         type: string
        zbox_branch:
         description: '0box branch to deploy'
         default: 'staging'
@@ -151,9 +156,9 @@ jobs:
           exit 0
         fi
 
-        PR_ID=$(curl --silent -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/search/issues?q=sha:$SHORT_SHA | jq --raw-output .items[0].number)
-        if [ -z "$PR_ID" ];then
-          echo "::error title=$3 docker image not found::$3 docker image could not be found with tag [${TAG}-${SHORT_SHA}]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again"
+        PR_ID=$(curl --silent -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/search/issues?q=is:pr+org:0chain+sha:$SHORT_SHA | jq --raw-output .items[0].number)
+        if [[ -z "$PR_ID" || "$PR_ID" == "null" ]];then
+          echo "::error title=$3 docker image not found::$3 docker image could not be found with tag [${TAG}-${SHORT_SHA}] and PR is not open. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again"
           exit 1
         fi
 
@@ -170,6 +175,11 @@ jobs:
 
         exit_code=0
         MERGE_SHORT_SHA=$(curl --silent -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/repos/0chain/$1/pulls/$PR_ID | jq --raw-output .merge_commit_sha | head -c 8)
+
+        if [[ -z "$MERGE_SHORT_SHA" || "$MERGE_SHORT_SHA" == "null" ]];then
+          echo "::error title=$3 docker image not found::$3 docker image could not be found with tag [pr-$PR_ID-$SHORT_SHA] and PR merge commit not found. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again"
+          exit 1
+        fi
 
         echo "Searching for image [merge-$MERGE_SHORT_SHA]..."
         docker pull 0chaindev/$3:merge-$MERGE_SHORT_SHA > /dev/null 2>&1 || exit_code=$?
@@ -192,6 +202,7 @@ jobs:
         ./get_tag.sh 0chain ${{ inputs.sharder_branch }} sharder
         ./get_tag.sh blobber ${{ inputs.blobber_branch }} blobber
         ./get_tag.sh blobber ${{ inputs.validator_branch }} validator
+        ./get_tag.sh token_bridge_authserver ${{ inputs.authorizer_branch }} authorizer
         ./get_tag.sh 0box ${{ inputs.zbox_branch }} 0box
         ./get_tag.sh 0block ${{ inputs.zblock_branch }} 0block
         ./get_tag.sh 0dns ${{ inputs.zdns_branch }} 0dns
@@ -217,6 +228,7 @@ jobs:
         explorer_branch: ${{ inputs.explorer_branch }}
         zproxy_branch: ${{ inputs.zproxy_branch }}
         zsearch_branch: ${{ inputs.zsearch_branch }}
+        authorizer_branch: ${{ inputs.authorizer_branch }}
         skip_tests: ${{ inputs.skip_tests }}
         github_token: ${{ secrets.SVC_ACCOUNT_SECRET }}
 
@@ -230,6 +242,7 @@ jobs:
         sharder_image: ${{ env.SHARDER_TAG }}
         blobber_image: ${{ env.BLOBBER_TAG }}
         validator_image: ${{ env.VALIDATOR_TAG }}
+        authorizer_image: ${{ env.AUTHORIZER_TAG }}
         zbox_image: ${{ env.ZBOX_TAG }}
         zblock_image: ${{ env.ZBLOCK_TAG }}
         zdns_image: ${{ env.ZDNS_TAG }}
@@ -273,5 +286,6 @@ jobs:
         explorer_branch: ${{ inputs.explorer_branch }}
         zproxy_branch: ${{ inputs.zproxy_branch }}
         zsearch_branch: ${{ inputs.zsearch_branch }}
+        authorizer_branch: ${{ inputs.authorizer_branch }}
         skip_tests: ${{ inputs.skip_tests }}
         github_token: ${{ secrets.SVC_ACCOUNT_SECRET }}
